
var webp_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(webp_dec) {
  webp_dec = webp_dec || {};


var e;e||(e=typeof webp_dec !== 'undefined' ? webp_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var t={},u;for(u in e)e.hasOwnProperty(u)&&(t[u]=e[u]);var v=!1,w=!1,ca=!1,da=!1;v="object"===typeof window;w="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!v&&!ca&&!w;var x="",z,A,ea,fa;
if(ca)x=w?require("path").dirname(x)+"/":__dirname+"/",z=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},A=function(a){a=z(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),e.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=
typeof read&&(z=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(v||w)w?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==
x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});e.print||console.log.bind(console);var C=e.printErr||console.warn.bind(console);for(u in t)t.hasOwnProperty(u)&&(e[u]=t[u]);t=null;var D;e.wasmBinary&&(D=e.wasmBinary);var noExitRuntime;
e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var E,ha=!1;function assert(a,b){a||B("Assertion failed: "+b)}var ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b,c){var d=F;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function la(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&G[c];)++c;c<<=1;if(32<c-a&&ka)return ka.decode(F.subarray(a,c));c=0;for(d="";;){var f=H[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function ma(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)H[b>>1]=a.charCodeAt(f),b+=2;H[b>>1]=0;return b-d}function na(a){return 2*a.length}
function oa(a,b){for(var c=0,d="";!(c>=b/4);){var f=I[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function pa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}I[b>>2]=g;b+=4;if(b+4>c)break}I[b>>2]=0;return b-d}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,ra,F,H,G,I,L,sa,ta;function ua(a){K=a;e.HEAP8=ra=new Int8Array(a);e.HEAP16=H=new Int16Array(a);e.HEAP32=I=new Int32Array(a);e.HEAPU8=F=new Uint8Array(a);e.HEAPU16=G=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=sa=new Float32Array(a);e.HEAPF64=ta=new Float64Array(a)}var va=e.INITIAL_MEMORY||16777216;e.wasmMemory?E=e.wasmMemory:E=new WebAssembly.Memory({initial:va/65536,maximum:32768});
E&&(K=E.buffer);va=K.byteLength;ua(K);var M,wa=[],xa=[],ya=[],za=[];function Aa(){var a=e.preRun.shift();wa.unshift(a)}var N=0,Ba=null,P=null;e.preloadedImages={};e.preloadedAudios={};function B(a){if(e.onAbort)e.onAbort(a);C(a);ha=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ca(a){var b=Q;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Da(){return Ca("data:application/octet-stream;base64,")}
var Q="webp_dec.wasm";if(!Da()){var Ea=Q;Q=e.locateFile?e.locateFile(Ea,x):x+Ea}function Fa(){try{if(D)return new Uint8Array(D);if(A)return A(Q);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Ga(){return D||!v&&!w||"function"!==typeof fetch||Ca("file://")?Promise.resolve().then(Fa):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Fa()})}
function R(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.G;"number"===typeof c?void 0===b.C?M.get(c)():M.get(c)(b.C):c(void 0===b.C?null:b.C)}}}function Ha(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ia=void 0;function S(a){for(var b="";F[a];)b+=Ia[F[a++]];return b}var T={},U={},V={};
function Ja(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ka(a,b){a=Ja(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function La(a){var b=Error,c=Ka(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ma=void 0;function W(a){throw new Ma(a);}var Na=void 0;
function Oa(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new Na("Mismatched type converter count");for(var h=0;h<d.length;++h)X(d[h],k[h])}var d=[];d.forEach(function(k){V[k]=a});var f=Array(a.length),g=[],n=0;a.forEach(function(k,h){U.hasOwnProperty(k)?f[h]=U[k]:(g.push(k),T.hasOwnProperty(k)||(T[k]=[]),T[k].push(function(){f[h]=U[k];++n;n===g.length&&c(f)}))});0===g.length&&c(f)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(U.hasOwnProperty(a)){if(c.H)return;W("Cannot register type '"+d+"' twice")}U[a]=b;delete V[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(function(f){f()}))}var Pa=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Qa(a){4<a&&0===--Y[a].D&&(Y[a]=void 0,Pa.push(a))}function Ra(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Pa.length?Pa.pop():Y.length;Y[b]={D:1,value:a};return b}}function Sa(a){return this.fromWireType(L[a>>2])}function Ta(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Wa(a,b){switch(b){case 2:return function(c){return this.fromWireType(sa[c>>2])};case 3:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Xa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ka(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ya(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Za(a,b){var c=e;if(void 0===c[a].A){var d=c[a];c[a]=function(){c[a].A.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].A+")!");return c[a].A[arguments.length].apply(this,arguments)};c[a].A=[];c[a].A[d.F]=d}}
function $a(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].A&&void 0!==e[a].A[c])&&W("Cannot register public name '"+a+"' twice"),Za(a,a),e.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].A[c]=b):(e[a]=b,void 0!==c&&(e[a].J=c))}function ab(a,b){for(var c=[],d=0;d<a;d++)c.push(I[(b>>2)+d]);return c}
function bb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=M.get(b).apply(null,c);return f}}function cb(a,b){a=S(a);var c=-1!=a.indexOf("j")?bb(a,b):M.get(b);"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}
var db=void 0;function eb(a){a=fb(a);var b=S(a);Z(a);return b}function gb(a,b){function c(g){f[g]||U[g]||(V[g]?V[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new db(a+": "+d.map(eb).join([", "]));}
function hb(a,b,c){switch(b){case 0:return c?function(d){return ra[d]}:function(d){return F[d]};case 1:return c?function(d){return H[d>>1]}:function(d){return G[d>>1]};case 2:return c?function(d){return I[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var ib={};function jb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function kb(a,b){var c=U[a];void 0===c&&W(b+" has unknown type "+eb(a));return c}
for(var lb={},mb=Array(256),nb=0;256>nb;++nb)mb[nb]=String.fromCharCode(nb);Ia=mb;Ma=e.BindingError=La("BindingError");Na=e.InternalError=La("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};db=e.UnboundTypeError=La("UnboundTypeError");xa.push({G:function(){ob()}});
var qb={g:function(){},o:function(a,b,c,d,f){var g=Ha(c);b=S(b);X(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(n){if(1===c)var k=ra;else if(2===c)k=H;else if(4===c)k=I;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[n>>g])},B:null})},r:function(a,b){b=S(b);X(a,{name:b,fromWireType:function(c){var d=Y[c].value;Qa(c);return d},toWireType:function(c,d){return Ra(d)},argPackAdvance:8,
readValueFromPointer:Sa,B:null})},n:function(a,b,c){c=Ha(c);b=S(b);X(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ta(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Wa(b,c),B:null})},j:function(a,b,c,d,f,g){var n=ab(b,c);a=S(a);f=cb(d,f);$a(a,function(){gb("Cannot call "+a+" due to unbound types",n)},b-1);Oa(n,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,q=f,
m=h.length;2>m&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var r=null!==h[1]&&!1,y=!1,l=1;l<h.length;++l)if(null!==h[l]&&void 0===h[l].B){y=!0;break}var Ua="void"!==h[0].name,J="",O="";for(l=0;l<m-2;++l)J+=(0!==l?", ":"")+"arg"+l,O+=(0!==l?", ":"")+"arg"+l+"Wired";p="return function "+Ja(p)+"("+J+") {\nif (arguments.length !== "+(m-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(m-2)+" args!');\n}\n";
y&&(p+="var destructors = [];\n");var Va=y?"destructors":"null";J="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[W,q,g,Ya,h[0],h[1]];r&&(p+="var thisWired = classParam.toWireType("+Va+", this);\n");for(l=0;l<m-2;++l)p+="var arg"+l+"Wired = argType"+l+".toWireType("+Va+", arg"+l+"); // "+h[l+2].name+"\n",J.push("argType"+l),q.push(h[l+2]);r&&(O="thisWired"+(0<O.length?", ":"")+O);p+=(Ua?"var rv = ":"")+"invoker(fn"+(0<O.length?", ":"")+O+");\n";if(y)p+="runDestructors(destructors);\n";
else for(l=r?1:2;l<h.length;++l)m=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==h[l].B&&(p+=m+"_dtor("+m+"); // "+h[l].name+"\n",J.push(m+"_dtor"),q.push(h[l].B));Ua&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");J.push(p+"}\n");h=Xa(J).apply(null,q);l=b-1;if(!e.hasOwnProperty(k))throw new Na("Replacing nonexistant public symbol");void 0!==e[k].A&&void 0!==l?e[k].A[l]=h:(e[k]=h,e[k].F=l);return[]})},c:function(a,b,c,d,f){function g(p){return p}b=S(b);-1===f&&(f=4294967295);var n=Ha(c);
if(0===d){var k=32-8*c;g=function(p){return p<<k>>>k}}var h=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:g,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Ta(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+Ta(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return h?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:hb(b,n,0!==d),B:null})},
b:function(a,b,c){function d(g){g>>=2;var n=L;return new f(K,n[g+1],n[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);X(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{H:!0})},i:function(a,b){b=S(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(d){var f=L[d>>2];if(c)for(var g=d+4,n=0;n<=f;++n){var k=d+4+n;if(n==f||0==F[k]){if(g){var h=g;var p=F,q=h+(k-g);for(g=h;p[g]&&!(g>=q);)++g;if(16<g-h&&p.subarray&&
ia)h=ia.decode(p.subarray(h,g));else{for(q="";h<g;){var m=p[h++];if(m&128){var r=p[h++]&63;if(192==(m&224))q+=String.fromCharCode((m&31)<<6|r);else{var y=p[h++]&63;m=224==(m&240)?(m&15)<<12|r<<6|y:(m&7)<<18|r<<12|y<<6|p[h++]&63;65536>m?q+=String.fromCharCode(m):(m-=65536,q+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else q+=String.fromCharCode(m)}h=q}}else h="";if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;g=k+1}}else{l=Array(f);for(n=0;n<f;++n)l[n]=String.fromCharCode(F[d+4+n]);
l=l.join("")}Z(d);return l},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||W("Cannot pass non-string to std::string");var n=(c&&g?function(){for(var p=0,q=0;q<f.length;++q){var m=f.charCodeAt(q);55296<=m&&57343>=m&&(m=65536+((m&1023)<<10)|f.charCodeAt(++q)&1023);127>=m?++p:p=2047>=m?p+2:65535>=m?p+3:p+4}return p}:function(){return f.length})(),k=pb(4+n+1);L[k>>2]=
n;if(c&&g)ja(f,k+4,n+1);else if(g)for(g=0;g<n;++g){var h=f.charCodeAt(g);255<h&&(Z(k),W("String has UTF-16 code units that do not fit in 8 bits"));F[k+4+g]=h}else for(g=0;g<n;++g)F[k+4+g]=f[g];null!==d&&d.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:Sa,B:function(d){Z(d)}})},h:function(a,b,c){c=S(c);if(2===b){var d=la;var f=ma;var g=na;var n=function(){return G};var k=1}else 4===b&&(d=oa,f=pa,g=qa,n=function(){return L},k=2);X(a,{name:c,fromWireType:function(h){for(var p=L[h>>2],q=n(),
m,r=h+4,y=0;y<=p;++y){var l=h+4+y*b;if(y==p||0==q[l>>k])r=d(r,l-r),void 0===m?m=r:(m+=String.fromCharCode(0),m+=r),r=l+b}Z(h);return m},toWireType:function(h,p){"string"!==typeof p&&W("Cannot pass non-string to C++ string type "+c);var q=g(p),m=pb(4+q+b);L[m>>2]=q>>k;f(p,m+4,q+b);null!==h&&h.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Sa,B:function(h){Z(h)}})},p:function(a,b){b=S(b);X(a,{I:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},e:Qa,f:function(a){if(0===
a)return Ra(jb());var b=ib[a];a=void 0===b?S(a):b;return Ra(jb()[a])},k:function(a){4<a&&(Y[a].D+=1)},l:function(a,b,c,d){a||W("Cannot use deleted val. handle = "+a);a=Y[a].value;var f=lb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var n="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)n+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+
g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",n+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(kb,e,Ra);lb[b]=f}return f(a,c,d)},m:function(){B()},q:function(a,b,c){F.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=F.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{E.grow(Math.min(2147483648,d)-K.byteLength+65535>>>
16);ua(E.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},a:E};
(function(){function a(f){e.asm=f.exports;M=e.asm.s;N--;e.monitorRunDependencies&&e.monitorRunDependencies(N);0==N&&(null!==Ba&&(clearInterval(Ba),Ba=null),P&&(f=P,P=null,f()))}function b(f){a(f.instance)}function c(f){return Ga().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){C("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:qb};N++;e.monitorRunDependencies&&e.monitorRunDependencies(N);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return C("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return D||"function"!==typeof WebAssembly.instantiateStreaming||Da()||Ca("file://")||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){C("wasm streaming compile failed: "+g);C("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var ob=e.___wasm_call_ctors=function(){return(ob=e.___wasm_call_ctors=e.asm.t).apply(null,arguments)},pb=e._malloc=function(){return(pb=e._malloc=e.asm.u).apply(null,arguments)},Z=e._free=function(){return(Z=e._free=e.asm.v).apply(null,arguments)},fb=e.___getTypeName=function(){return(fb=e.___getTypeName=e.asm.w).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.x).apply(null,arguments)};var rb;
P=function sb(){rb||tb();rb||(P=sb)};
function tb(){function a(){if(!rb&&(rb=!0,e.calledRun=!0,!ha)){R(xa);R(ya);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();za.unshift(b)}R(za)}}if(!(0<N)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();R(wa);0<N||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=tb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;tb();


  return webp_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = webp_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return webp_dec; });
    else if (typeof exports === 'object')
      exports["webp_dec"] = webp_dec;
    