
var wp2_enc_mt = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(wp2_enc_mt) {
  wp2_enc_mt = wp2_enc_mt || {};


function e(){h.buffer!=n&&p(h.buffer);return aa}function u(){h.buffer!=n&&p(h.buffer);return ba}function ca(){h.buffer!=n&&p(h.buffer);return da}function ea(){h.buffer!=n&&p(h.buffer);return fa}function w(){h.buffer!=n&&p(h.buffer);return ha}function y(){h.buffer!=n&&p(h.buffer);return ia}function ja(){h.buffer!=n&&p(h.buffer);return la}function ma(){h.buffer!=n&&p(h.buffer);return na}var z;z||(z=typeof wp2_enc_mt !== 'undefined' ? wp2_enc_mt : {});var oa,pa;
z.ready=new Promise(function(a,b){oa=a;pa=b});var qa={},A;for(A in z)z.hasOwnProperty(A)&&(qa[A]=z[A]);var ra=!1,B=!1,C=!1,sa=!1;ra="object"===typeof window;B="function"===typeof importScripts;C="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;sa=!ra&&!C&&!B;var D=z.ENVIRONMENT_IS_PTHREAD||!1;D&&(n=z.buffer);var F="";function ta(a){return z.locateFile?z.locateFile(a,F):F+a}var G,I,J,K;
if(C){F=B?require("path").dirname(F)+"/":__dirname+"/";G=function(a,b){J||(J=require("fs"));K||(K=require("path"));a=K.normalize(a);return J.readFileSync(a,b?null:"utf8")};I=function(a){a=G(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ua))throw a;});process.on("unhandledRejection",L);z.inspect=function(){return"[Emscripten Module object]"};
var va;try{va=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=va.Worker}else if(sa)"undefined"!=typeof read&&(G=function(a){return read(a)}),I=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ra||B)B?F=self.location.href:"undefined"!==typeof document&&document.currentScript&&(F=document.currentScript.src),_scriptDir&&(F=_scriptDir),0!==F.indexOf("blob:")?F=F.substr(0,F.lastIndexOf("/")+1):F="",C?(G=function(a,b){J||(J=require("fs"));K||(K=require("path"));a=K.normalize(a);return J.readFileSync(a,b?null:"utf8")},I=function(a){a=G(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(G=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},B&&(I=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));C&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var wa=z.print||console.log.bind(console),M=z.printErr||console.warn.bind(console);for(A in qa)qa.hasOwnProperty(A)&&(z[A]=qa[A]);qa=null;var xa,ya;z.wasmBinary&&(ya=z.wasmBinary);var noExitRuntime;
z.noExitRuntime&&(noExitRuntime=z.noExitRuntime);"object"!==typeof WebAssembly&&L("no native wasm support detected");var h,Aa,threadInfoStruct=0,selfThreadId=0,Ba=!1;function assert(a,b){a||L("Assertion failed: "+b)}
function Ca(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function N(a,b){return a?Ca(u(),a,b):""}
function Da(a,b,c){var d=u();if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Fa(a,b){for(var c=0,d="";;){var f=ca()[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function Ga(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);ca()[b>>1]=g;b+=2}ca()[b>>1]=0;return b-d}
function Ha(a){return 2*a.length}function Ia(a,b){for(var c=0,d="";!(c>=b/4);){var f=w()[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function Ja(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}w()[b>>2]=g;b+=4;if(b+4>c)break}w()[b>>2]=0;return b-d}
function Ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var n,aa,ba,da,fa,ha,ia,la,na;function p(a){n=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=da=new Int16Array(a);z.HEAP32=ha=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=fa=new Uint16Array(a);z.HEAPU32=ia=new Uint32Array(a);z.HEAPF32=la=new Float32Array(a);z.HEAPF64=na=new Float64Array(a)}var La=z.INITIAL_MEMORY||16777216;
if(D)h=z.wasmMemory,n=z.buffer;else if(z.wasmMemory)h=z.wasmMemory;else if(h=new WebAssembly.Memory({initial:La/65536,maximum:32768,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw M("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),C&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");h&&(n=h.buffer);La=n.byteLength;p(n);var Ma,Na=[],Oa=[],Pa=[],Qa=[];function Ra(){var a=z.preRun.shift();Na.unshift(a)}var P=0,Sa=null,Ta=null;z.preloadedImages={};z.preloadedAudios={};function L(a){if(z.onAbort)z.onAbort(a);D&&console.error("Pthread aborting at "+Error().stack);M(a);Ba=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");pa(a);throw a;}
function Ua(a){var b=Q;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Va(){return Ua("data:application/octet-stream;base64,")}var Q="wp2_enc_mt.wasm";Va()||(Q=ta(Q));function Wa(){try{if(ya)return new Uint8Array(ya);if(I)return I(Q);throw"both async and sync fetching of the wasm failed";}catch(a){L(a)}}
function Xa(){return ya||!ra&&!B||"function"!==typeof fetch||Ua("file://")?Promise.resolve().then(Wa):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}var Za={126181:function(a,b){setTimeout(function(){Ya(a,b)},0)},126259:function(){throw"Canceled!";}};
function $a(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(z);else{var c=b.lb;"number"===typeof c?void 0===b.La?Ma.get(c)():Ma.get(c)(b.La):c(void 0===b.La?null:b.La)}}}function ab(a,b,c){var d;-1!=a.indexOf("j")?d=c&&c.length?z["dynCall_"+a].apply(null,[b].concat(c)):z["dynCall_"+a].call(null,b):d=Ma.get(b).apply(null,c);return d}z.dynCall=ab;var R=0,bb=0,cb=0;function db(a,b,c){R=a|0;cb=b|0;bb=c|0}z.registerPthreadPtr=db;
function eb(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(w(),S.Ia>>2),d=0;if(c==a&&Atomics.compareExchange(w(),S.Ia>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(w(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}z._emscripten_futex_wake=eb;
function fb(a){if(D)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";w()[a+12>>2]=0;(a=S.Ea[a])&&S.Ra(a.worker)}
var S={Ob:1,Vb:{eb:0,fb:0},Ca:[],Ga:[],tb:function(){for(var a=navigator.hardwareConcurrency,b=0;b<a;++b)S.Xa()},ub:function(){S.Aa=T(232);for(var a=0;58>a;++a)y()[S.Aa/4+a]=0;w()[S.Aa+12>>2]=S.Aa;a=S.Aa+156;w()[a>>2]=a;var b=T(512);for(a=0;128>a;++a)y()[b/4+a]=0;Atomics.store(y(),S.Aa+104>>2,b);Atomics.store(y(),S.Aa+40>>2,S.Aa);Atomics.store(y(),S.Aa+44>>2,42);S.$a();db(S.Aa,!B,1);gb(S.Aa)},vb:function(){S.$a();oa(z);S.receiveObjectTransfer=S.Ab;S.setThreadStatus=S.Bb;S.threadCancel=S.Lb;S.threadExit=
S.Mb},$a:function(){S.Ia=hb},Ea:{},Wa:[],Bb:function(){},cb:function(){for(;0<S.Wa.length;)S.Wa.pop()();D&&threadInfoStruct&&ib()},Mb:function(a){var b=R|0;b&&(Atomics.store(y(),b+4>>2,a),Atomics.store(y(),b+0>>2,1),Atomics.store(y(),b+60>>2,1),Atomics.store(y(),b+64>>2,0),S.cb(),eb(b+0,2147483647),db(0,0,0),threadInfoStruct=0,D&&postMessage({cmd:"exit"}))},Lb:function(){S.cb();Atomics.store(y(),threadInfoStruct+4>>2,-1);Atomics.store(y(),threadInfoStruct+0>>2,1);eb(threadInfoStruct+0,2147483647);
threadInfoStruct=selfThreadId=0;db(0,0,0);postMessage({cmd:"cancelDone"})},bc:function(){for(var a in S.Ea){var b=S.Ea[a];b&&b.worker&&S.Ra(b.worker)}S.Ea={};for(a=0;a<S.Ca.length;++a){var c=S.Ca[a];c.terminate()}S.Ca=[];for(a=0;a<S.Ga.length;++a)c=S.Ga[a],b=c.Ba,S.Ua(b),c.terminate();S.Ga=[]},Ua:function(a){if(a){if(a.threadInfoStruct){var b=w()[a.threadInfoStruct+104>>2];w()[a.threadInfoStruct+104>>2]=0;U(b);U(a.threadInfoStruct)}a.threadInfoStruct=0;a.Sa&&a.Ha&&U(a.Ha);a.Ha=0;a.worker&&(a.worker.Ba=
null)}},Ra:function(a){delete S.Ea[a.Ba.gb];S.Ca.push(a);S.Ga.splice(S.Ga.indexOf(a),1);S.Ua(a.Ba);a.Ba=void 0},Ab:function(){},ab:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.Ba&&(S.Ta=a.Ba.threadInfoStruct);if(d.targetThread&&d.targetThread!=(R|0)){var g=S.Ea[d.ac];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===
f)jb();else if("spawnThread"===f)kb(c.data);else if("cleanupThread"===f)fb(d.thread);else if("killThread"===f){c=d.thread;if(D)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";w()[c+12>>2]=0;c=S.Ea[c];c.worker.terminate();S.Ua(c);S.Ga.splice(S.Ga.indexOf(c.worker),1);c.worker.Ba=void 0}else if("cancelThread"===f){c=d.thread;if(D)throw"Internal Error! cancelThread() can only ever be called from main application thread!";
if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";S.Ea[c].worker.postMessage({cmd:"cancel"})}else"loaded"===f?(a.loaded=!0,b&&b(a),a.Na&&(a.Na(),delete a.Na)):"print"===f?wa("Thread "+d.threadId+": "+d.text):"printErr"===f?M("Thread "+d.threadId+": "+d.text):"alert"===f?alert("Thread "+d.threadId+": "+d.text):"exit"===f?a.Ba&&Atomics.load(y(),a.Ba.gb+68>>2)&&S.Ra(a):"cancelDone"===f?S.Ra(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):M("worker sent an unknown command "+
f));S.Ta=void 0};a.onerror=function(c){M("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};C&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:Aa})},Xa:function(){var a=ta("wp2_enc_mt.worker.js");S.Ca.push(new Worker(a))},mb:function(){0==S.Ca.length&&(S.Xa(),S.ab(S.Ca[0]));return 0<S.Ca.length?S.Ca.pop():null},Pb:function(a){for(a=
performance.now()+a;performance.now()<a;);}};z.establishStackSpace=function(a){lb(a)};z.getNoExitRuntime=function(){return noExitRuntime};var mb;C?mb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:D?mb=function(){return performance.now()-z.__performance_now_clock_drift}:"undefined"!==typeof dateNow?mb=dateNow:mb=function(){return performance.now()};function nb(a,b){S.Wa.push(function(){Ma.get(a)(b)})}
function ob(a){this.Ma=a-16;this.Gb=function(b){w()[this.Ma+8>>2]=b};this.Db=function(b){w()[this.Ma+0>>2]=b};this.Eb=function(){w()[this.Ma+4>>2]=0};this.Cb=function(){var b=0;e()[this.Ma+12>>0]=b};this.Fb=function(){var b=0;e()[this.Ma+13>>0]=b};this.rb=function(b,c){this.Gb(b);this.Db(c);this.Eb();this.Cb();this.Fb()}}function pb(){return 0<pb.hb}var qb={};function rb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function sb(a){return this.fromWireType(y()[a>>2])}var tb={},V={},ub={};
function vb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function wb(a,b){a=vb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function xb(a){var b=Error,c=wb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var yb=void 0;
function zb(a,b,c){function d(m){m=c(m);if(m.length!==a.length)throw new yb("Mismatched type converter count");for(var l=0;l<a.length;++l)W(a[l],m[l])}a.forEach(function(m){ub[m]=b});var f=Array(b.length),g=[],k=0;b.forEach(function(m,l){V.hasOwnProperty(m)?f[l]=V[m]:(g.push(m),tb.hasOwnProperty(m)||(tb[m]=[]),tb[m].push(function(){f[l]=V[m];++k;k===g.length&&d(f)}))});0===g.length&&d(f)}
function Ab(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Bb=void 0;function X(a){for(var b="";u()[a];)b+=Bb[u()[a++]];return b}var Cb=void 0;function Y(a){throw new Cb(a);}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Y('type "'+d+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.qb)return;Y("Cannot register type '"+d+"' twice")}V[a]=b;delete ub[a];tb.hasOwnProperty(a)&&(b=tb[a],delete tb[a],b.forEach(function(f){f()}))}var Db=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Eb(a){4<a&&0===--Z[a].Va&&(Z[a]=void 0,Db.push(a))}function Fb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Db.length?Db.pop():Z.length;Z[b]={Va:1,value:a};return b}}function Gb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Hb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja()[c>>2])};case 3:return function(c){return this.fromWireType(ma()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ib(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=wb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Jb(a,b){var c=z;if(void 0===c[a].Da){var d=c[a];c[a]=function(){c[a].Da.hasOwnProperty(arguments.length)||Y("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Da+")!");return c[a].Da[arguments.length].apply(this,arguments)};c[a].Da=[];c[a].Da[d.ib]=d}}
function Kb(a,b,c){z.hasOwnProperty(a)?((void 0===c||void 0!==z[a].Da&&void 0!==z[a].Da[c])&&Y("Cannot register public name '"+a+"' twice"),Jb(a,a),z.hasOwnProperty(c)&&Y("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),z[a].Da[c]=b):(z[a]=b,void 0!==c&&(z[a].Yb=c))}function Lb(a,b){for(var c=[],d=0;d<a;d++)c.push(w()[(b>>2)+d]);return c}
function Mb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];return ab(a,b,c)}}function Nb(a,b){a=X(a);var c=-1!=a.indexOf("j")?Mb(a,b):Ma.get(b);"function"!==typeof c&&Y("unknown function pointer with signature "+a+": "+b);return c}var Ob=void 0;function Pb(a){a=Qb(a);var b=X(a);U(a);return b}
function Rb(a,b){function c(g){f[g]||V[g]||(ub[g]?ub[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Ob(a+": "+d.map(Pb).join([", "]));}function Sb(a,b,c){switch(b){case 0:return c?function(d){return e()[d]}:function(d){return u()[d]};case 1:return c?function(d){return ca()[d>>1]}:function(d){return ea()[d>>1]};case 2:return c?function(d){return w()[d>>2]}:function(d){return y()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Tb={};
function Ub(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Vb(a,b){var c=V[a];void 0===c&&Y(b+" has unknown type "+Pb(a));return c}var Wb={};
function Xb(){C||B||(xa||(xa={}),xa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(xa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,M("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function Yb(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(ra){if(Atomics.load(w(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(w(),S.Ia>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(w(),S.Ia>>2,0),-73;d=Atomics.exchange(w(),S.Ia>>2,0);if(0==d)break;jb();if(Atomics.load(w(),a>>2)!=b)return-6;Atomics.exchange(w(),S.Ia>>2,a)}return 0}a=Atomics.wait(w(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Zb(a,b){for(var c=arguments.length-2,d=$b(),f=ac(8*c),g=f>>3,k=0;k<c;k++)ma()[g+k]=arguments[2+k];c=bc(a,c,f,b);lb(d);return c}var cc=[],dc=[],ec=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function fc(a){a=2<a?N(a):a;return ec[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function hc(a,b,c){var d=fc(a);if(!d)return-4;d.Qa&&(w()[d.Qa>>2]=b,w()[d.Qa+4>>2]=c);if(d.bb||!d.Rb)d.bb&&(d=d.bb),a=!1,d.Pa&&d.Pa.Oa&&(a=d.Pa.Oa.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Pa.Oa.viewport(0,0,b,c);else{if(d.Qa){d=w()[d.Qa+8>>2];a=a?N(a):"";var f=$b(),g=ac(12),k=0;if(a){k=Ea(a)+1;var m=T(k);Da(a,m,k);k=m}w()[g>>2]=k;w()[g+4>>2]=b;w()[g+8>>2]=c;ic(0,d,657457152,0,k,g);lb(f);return 1}return-4}return 0}
function jc(a,b,c){return D?Zb(1,1,a,b,c):hc(a,b,c)}function kc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function lc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function mc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function nc(a){a||(a=oc);if(!a.sb){a.sb=!0;var b=a.Oa;kc(b);lc(b);mc(b);b.Sb=b.getExtension("EXT_disjoint_timer_query");b.Xb=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var oc,pc=["default","low-power","high-performance"],qc=[null,[],[]];function rc(a){return D?Zb(2,1,a):0}function sc(a,b,c,d,f){if(D)return Zb(3,1,a,b,c,d,f)}function tc(a,b,c,d){if(D)return Zb(4,1,a,b,c,d);for(var f=0,g=0;g<c;g++){for(var k=w()[b+8*g>>2],m=w()[b+(8*g+4)>>2],l=0;l<m;l++){var r=u()[k+l],q=qc[a];0===r||10===r?((1===a?wa:M)(Ca(q,0)),q.length=0):q.push(r)}f+=m}w()[d>>2]=f;return 0}
function kb(a){if(D)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=S.mb();if(void 0!==b.Ba)throw"Internal error!";if(!a.Ja)throw"Internal error, no pthread ptr!";S.Ga.push(b);for(var c=T(512),d=0;128>d;++d)w()[c+4*d>>2]=0;var f=a.Ha+a.Ka;d=S.Ea[a.Ja]={worker:b,Ha:a.Ha,Ka:a.Ka,Sa:a.Sa,gb:a.Ja,threadInfoStruct:a.Ja};var g=d.threadInfoStruct>>2;Atomics.store(y(),g,0);Atomics.store(y(),g+1,0);Atomics.store(y(),g+2,0);Atomics.store(y(),g+17,a.detached);
Atomics.store(y(),g+26,c);Atomics.store(y(),g+12,0);Atomics.store(y(),g+10,d.threadInfoStruct);Atomics.store(y(),g+11,42);Atomics.store(y(),g+27,a.Ka);Atomics.store(y(),g+21,a.Ka);Atomics.store(y(),g+20,f);Atomics.store(y(),g+29,f);Atomics.store(y(),g+30,a.detached);Atomics.store(y(),g+32,a.eb);Atomics.store(y(),g+33,a.fb);c=uc()+40;Atomics.store(y(),g+44,c);b.Ba=d;var k={cmd:"run",start_routine:a.Kb,arg:a.La,threadInfoStruct:a.Ja,selfThreadId:a.Ja,parentThreadId:a.xb,stackBase:a.Ha,stackSize:a.Ka};
b.Na=function(){k.time=performance.now();b.postMessage(k,a.Nb)};b.loaded&&(b.Na(),delete b.Na)}function vc(){return R|0}z._pthread_self=vc;
function wc(a,b){if(!a)return M("pthread_join attempted on a null thread pointer!"),71;if(D&&selfThreadId==a)return M("PThread "+a+" is attempting to join to itself!"),16;if(!D&&S.Aa==a)return M("Main thread "+a+" is attempting to join to itself!"),16;if(w()[a+12>>2]!==a)return M("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(y(),a+68>>2))return M("Attempted to join thread "+a+", which was already detached!"),28;for(Xb();;){var c=
Atomics.load(y(),a+0>>2);if(1==c)return c=Atomics.load(y(),a+4>>2),b&&(w()[b>>2]=c),Atomics.store(y(),a+68>>2,1),D?postMessage({cmd:"cleanupThread",thread:a}):fb(a),0;if(D&&threadInfoStruct&&!Atomics.load(y(),threadInfoStruct+60>>2)&&2==Atomics.load(y(),threadInfoStruct+0>>2))throw"Canceled!";D||jb();Yb(a+0,c,D?100:1)}}D||S.tb();yb=z.InternalError=xb("InternalError");for(var xc=Array(256),yc=0;256>yc;++yc)xc[yc]=String.fromCharCode(yc);Bb=xc;Cb=z.BindingError=xb("BindingError");
z.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};z.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};Ob=z.UnboundTypeError=xb("UnboundTypeError");var zc=[null,jc,rc,sc,tc];D||Oa.push({lb:function(){Ac()}});
var Dc={h:function(a,b,c,d){L("Assertion failed: "+N(a)+", at: "+[b?N(b):"unknown filename",c,d?N(d):"unknown function"])},Q:function(a){return T(a+16)+16},U:function(a,b){return nb(a,b)},P:function(a,b,c){(new ob(a)).rb(b,c);"uncaught_exception"in pb?pb.hb++:pb.hb=1;throw a;},x:function(a){var b=qb[a];delete qb[a];var c=b.yb,d=b.zb,f=b.Za,g=f.map(function(k){return k.pb}).concat(f.map(function(k){return k.Ib}));zb([a],g,function(k){var m={};f.forEach(function(l,r){var q=k[r],v=l.nb,x=l.ob,E=k[r+
f.length],t=l.Hb,za=l.Jb;m[l.kb]={read:function(H){return q.fromWireType(v(x,H))},write:function(H,O){var ka=[];t(za,H,E.toWireType(ka,O));rb(ka)}}});return[{name:b.name,fromWireType:function(l){var r={},q;for(q in m)r[q]=m[q].read(l);d(l);return r},toWireType:function(l,r){for(var q in m)if(!(q in r))throw new TypeError('Missing field:  "'+q+'"');var v=c();for(q in m)m[q].write(v,r[q]);null!==l&&l.push(d,v);return v},argPackAdvance:8,readValueFromPointer:sb,Fa:d}]})},N:function(a,b,c,d,f){var g=
Ab(c);b=X(b);W(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,m){return m?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var m=e();else if(2===c)m=ca();else if(4===c)m=w();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[k>>g])},Fa:null})},M:function(a,b){b=X(b);W(a,{name:b,fromWireType:function(c){var d=Z[c].value;Eb(c);return d},toWireType:function(c,d){return Fb(d)},argPackAdvance:8,readValueFromPointer:sb,Fa:null})},t:function(a,
b,c){c=Ab(c);b=X(b);W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Gb(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Hb(b,c),Fa:null})},w:function(a,b,c,d,f,g){var k=Lb(b,c);a=X(a);f=Nb(d,f);Kb(a,function(){Rb("Cannot call "+a+" due to unbound types",k)},b-1);zb([],k,function(m){var l=[m[0],null].concat(m.slice(1)),r=m=a,q=f,v=l.length;2>v&&Y("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var x=null!==l[1]&&!1,E=!1,t=1;t<l.length;++t)if(null!==l[t]&&void 0===l[t].Fa){E=!0;break}var za="void"!==l[0].name,H="",O="";for(t=0;t<v-2;++t)H+=(0!==t?", ":"")+"arg"+t,O+=(0!==t?", ":"")+"arg"+t+"Wired";r="return function "+vb(r)+"("+H+") {\nif (arguments.length !== "+(v-2)+") {\nthrowBindingError('function "+r+" called with ' + arguments.length + ' arguments, expected "+(v-2)+" args!');\n}\n";E&&(r+="var destructors = [];\n");var ka=E?"destructors":"null";H="throwBindingError invoker fn runDestructors retType classParam".split(" ");
q=[Y,q,g,rb,l[0],l[1]];x&&(r+="var thisWired = classParam.toWireType("+ka+", this);\n");for(t=0;t<v-2;++t)r+="var arg"+t+"Wired = argType"+t+".toWireType("+ka+", arg"+t+"); // "+l[t+2].name+"\n",H.push("argType"+t),q.push(l[t+2]);x&&(O="thisWired"+(0<O.length?", ":"")+O);r+=(za?"var rv = ":"")+"invoker(fn"+(0<O.length?", ":"")+O+");\n";if(E)r+="runDestructors(destructors);\n";else for(t=x?1:2;t<l.length;++t)v=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==l[t].Fa&&(r+=v+"_dtor("+v+"); // "+l[t].name+
"\n",H.push(v+"_dtor"),q.push(l[t].Fa));za&&(r+="var ret = retType.fromWireType(rv);\nreturn ret;\n");H.push(r+"}\n");l=Ib(H).apply(null,q);t=b-1;if(!z.hasOwnProperty(m))throw new yb("Replacing nonexistant public symbol");void 0!==z[m].Da&&void 0!==t?z[m].Da[t]=l:(z[m]=l,z[m].ib=t);return[]})},i:function(a,b,c,d,f){function g(r){return r}b=X(b);-1===f&&(f=4294967295);var k=Ab(c);if(0===d){var m=32-8*c;g=function(r){return r<<m>>>m}}var l=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(r,
q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Gb(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+Gb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return l?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Sb(b,k,0!==d),Fa:null})},g:function(a,b,c){function d(g){g>>=2;var k=y();return new f(n,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=X(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{qb:!0})},u:function(a,b){b=X(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=y()[d>>2];if(c)for(var g=d+4,k=0;k<=f;++k){var m=d+4+k;if(k==f||0==u()[m]){g=N(g,m-g);if(void 0===l)var l=g;else l+=String.fromCharCode(0),l+=g;g=m+1}}else{l=Array(f);for(k=0;k<f;++k)l[k]=String.fromCharCode(u()[d+4+k]);l=l.join("")}U(d);return l},toWireType:function(d,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||Y("Cannot pass non-string to std::string");var k=(c&&g?function(){return Ea(f)}:function(){return f.length})(),m=T(4+k+1);y()[m>>2]=k;if(c&&g)Da(f,m+4,k+1);else if(g)for(g=0;g<k;++g){var l=f.charCodeAt(g);255<l&&(U(m),Y("String has UTF-16 code units that do not fit in 8 bits"));u()[m+4+g]=l}else for(g=0;g<k;++g)u()[m+4+g]=f[g];null!==d&&d.push(U,m);return m},
argPackAdvance:8,readValueFromPointer:sb,Fa:function(d){U(d)}})},o:function(a,b,c){c=X(c);if(2===b){var d=Fa;var f=Ga;var g=Ha;var k=function(){return ea()};var m=1}else 4===b&&(d=Ia,f=Ja,g=Ka,k=function(){return y()},m=2);W(a,{name:c,fromWireType:function(l){for(var r=y()[l>>2],q=k(),v,x=l+4,E=0;E<=r;++E){var t=l+4+E*b;if(E==r||0==q[t>>m])x=d(x,t-x),void 0===v?v=x:(v+=String.fromCharCode(0),v+=x),x=t+b}U(l);return v},toWireType:function(l,r){"string"!==typeof r&&Y("Cannot pass non-string to C++ string type "+
c);var q=g(r),v=T(4+q+b);y()[v>>2]=q>>m;f(r,v+4,q+b);null!==l&&l.push(U,v);return v},argPackAdvance:8,readValueFromPointer:sb,Fa:function(l){U(l)}})},y:function(a,b,c,d,f,g){qb[a]={name:X(b),yb:Nb(c,d),zb:Nb(f,g),Za:[]}},k:function(a,b,c,d,f,g,k,m,l,r){qb[a].Za.push({kb:X(b),pb:c,nb:Nb(d,f),ob:g,Ib:k,Hb:Nb(m,l),Jb:r})},O:function(a,b){b=X(b);W(a,{Ub:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},I:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(D)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=S.Ea[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},q:Eb,L:function(a){if(0===a)return Fb(Ub());var b=Tb[a];a=void 0===b?X(a):b;return Fb(Ub()[a])},S:function(a){4<a&&(Z[a].Va+=1)},F:function(a,b,c,d){a||Y("Cannot use deleted val. handle = "+a);a=Z[a].value;var f=Wb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)k+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(Vb,z,Fb);Wb[b]=f}return f(a,c,d)},r:function(){L()},l:function(a,b,c){dc.length=0;var d;for(c>>=2;d=u()[b++];)(d=105>d)&&c&1&&c++,
dc.push(d?ma()[c++>>1]:w()[c]),++c;return Za[a].apply(null,dc)},J:Xb,p:function(){},e:Yb,f:eb,b:mb,n:function(){return cb|0},m:function(){return bb|0},C:function(a,b,c){u().copyWithin(a,b,b+c)},T:function(){return C?require("os").cpus().length:navigator.hardwareConcurrency},E:function(a,b,c){cc.length=b;c>>=3;for(var d=0;d<b;d++)cc[d]=ma()[c+d];return(0>a?Za[-a-1]:zc[a]).apply(null,cc)},j:function(a){a>>>=0;var b=u().length;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=
Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{h.grow(Math.min(2147483648,d)-n.byteLength+65535>>>16);p(h.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},G:function(a,b,c){return fc(a)?hc(a,b,c):jc(a,b,c)},d:function(){},H:function(a,b){var c={};b>>=2;c.alpha=!!w()[b];c.depth=!!w()[b+1];c.stencil=!!w()[b+2];c.antialias=!!w()[b+3];c.premultipliedAlpha=!!w()[b+4];c.preserveDrawingBuffer=!!w()[b+5];var d=w()[b+6];c.powerPreference=pc[d];c.failIfMajorPerformanceCaveat=
!!w()[b+7];c.wb=w()[b+8];c.Wb=w()[b+9];c.Ya=w()[b+10];c.jb=w()[b+11];c.Zb=w()[b+12];c.$b=w()[b+13];a=fc(a);!a||c.jb?c=0:(a=a.getContext("webgl",c))?(b=T(8),w()[b+4>>2]=R|0,d={Tb:b,attributes:c,version:c.wb,Oa:a},a.canvas&&(a.canvas.Pa=d),("undefined"===typeof c.Ya||c.Ya)&&nc(d),c=b):c=0;return c},K:rc,z:sc,s:tc,B:function(){S.ub()},a:h||z.wasmMemory,D:nb,v:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return M("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return M("pthread_create called with a null thread pointer!"),28;var f=[];if(D&&0===f.length)return Bc(687865856,a,b,c,d);var g=0,k=0,m=0,l=0;if(b){var r=w()[b>>2];r+=81920;g=w()[b+8>>2];k=0!==w()[b+12>>2];if(0===w()[b+16>>2]){var q=w()[b+20>>2],v=w()[b+24>>2];m=b+20;l=b+24;var x=S.Ta?S.Ta:R|0;if(m||l)if(x)if(w()[x+12>>2]!==x)M("pthread_getschedparam attempted on thread "+x+", which does not point to a valid thread, or does not exist anymore!");else{var E=Atomics.load(y(),x+108+20>>2);x=Atomics.load(y(),
x+108+24>>2);m&&(w()[m>>2]=E);l&&(w()[l>>2]=x)}else M("pthread_getschedparam called with a null thread pointer!");m=w()[b+20>>2];l=w()[b+24>>2];w()[b+20>>2]=q;w()[b+24>>2]=v}else m=w()[b+20>>2],l=w()[b+24>>2]}else r=2097152;(b=0==g)?g=Cc(16,r):(g-=r,assert(0<g));q=T(232);for(v=0;58>v;++v)y()[(q>>2)+v]=0;w()[a>>2]=q;w()[q+12>>2]=q;a=q+156;w()[a>>2]=a;c={Ha:g,Ka:r,Sa:b,eb:m,fb:l,detached:k,Kb:c,Ja:q,xb:R|0,La:d,Nb:f};D?(c.Qb="spawnThread",postMessage(c,f)):kb(c);return 0},R:function(a,b){return wc(a,
b)},c:vc,A:function(){}};
(function(){function a(f,g){z.asm=f.exports;Ma=z.asm.V;Aa=g;if(!D){var k=S.Ca.length;S.Ca.forEach(function(m){S.ab(m,function(){if(!--k&&(P--,z.monitorRunDependencies&&z.monitorRunDependencies(P),0==P&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta))){var l=Ta;Ta=null;l()}})})}}function b(f){a(f.instance,f.module)}function c(f){return Xa().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){M("failed to asynchronously prepare wasm: "+g);L(g)})}var d={a:Dc};D||(assert(!D,"addRunDependency cannot be used in a pthread worker"),
P++,z.monitorRunDependencies&&z.monitorRunDependencies(P));if(z.instantiateWasm)try{return z.instantiateWasm(d,a)}catch(f){return M("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ya||"function"!==typeof WebAssembly.instantiateStreaming||Va()||Ua("file://")||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){M("wasm streaming compile failed: "+g);M("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(pa);return{}})();var Ac=z.___wasm_call_ctors=function(){return(Ac=z.___wasm_call_ctors=z.asm.W).apply(null,arguments)},T=z._malloc=function(){return(T=z._malloc=z.asm.X).apply(null,arguments)},U=z._free=function(){return(U=z._free=z.asm.Y).apply(null,arguments)},Qb=z.___getTypeName=function(){return(Qb=z.___getTypeName=z.asm.Z).apply(null,arguments)};
z.___embind_register_native_and_builtin_types=function(){return(z.___embind_register_native_and_builtin_types=z.asm._).apply(null,arguments)};var uc=z._emscripten_get_global_libc=function(){return(uc=z._emscripten_get_global_libc=z.asm.$).apply(null,arguments)};z.___em_js__initPthreadsJS=function(){return(z.___em_js__initPthreadsJS=z.asm.aa).apply(null,arguments)};
var $b=z.stackSave=function(){return($b=z.stackSave=z.asm.ba).apply(null,arguments)},lb=z.stackRestore=function(){return(lb=z.stackRestore=z.asm.ca).apply(null,arguments)},ac=z.stackAlloc=function(){return(ac=z.stackAlloc=z.asm.da).apply(null,arguments)},Cc=z._memalign=function(){return(Cc=z._memalign=z.asm.ea).apply(null,arguments)};z._emscripten_main_browser_thread_id=function(){return(z._emscripten_main_browser_thread_id=z.asm.fa).apply(null,arguments)};
var ib=z.___pthread_tsd_run_dtors=function(){return(ib=z.___pthread_tsd_run_dtors=z.asm.ga).apply(null,arguments)},jb=z._emscripten_main_thread_process_queued_calls=function(){return(jb=z._emscripten_main_thread_process_queued_calls=z.asm.ha).apply(null,arguments)};z._emscripten_current_thread_process_queued_calls=function(){return(z._emscripten_current_thread_process_queued_calls=z.asm.ia).apply(null,arguments)};
var gb=z._emscripten_register_main_browser_thread_id=function(){return(gb=z._emscripten_register_main_browser_thread_id=z.asm.ja).apply(null,arguments)},Ya=z._do_emscripten_dispatch_to_thread=function(){return(Ya=z._do_emscripten_dispatch_to_thread=z.asm.ka).apply(null,arguments)};z._emscripten_async_run_in_main_thread=function(){return(z._emscripten_async_run_in_main_thread=z.asm.la).apply(null,arguments)};
z._emscripten_sync_run_in_main_thread=function(){return(z._emscripten_sync_run_in_main_thread=z.asm.ma).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_0=function(){return(z._emscripten_sync_run_in_main_thread_0=z.asm.na).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_1=function(){return(z._emscripten_sync_run_in_main_thread_1=z.asm.oa).apply(null,arguments)};
z._emscripten_sync_run_in_main_thread_2=function(){return(z._emscripten_sync_run_in_main_thread_2=z.asm.pa).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_xprintf_varargs=function(){return(z._emscripten_sync_run_in_main_thread_xprintf_varargs=z.asm.qa).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_3=function(){return(z._emscripten_sync_run_in_main_thread_3=z.asm.ra).apply(null,arguments)};
var Bc=z._emscripten_sync_run_in_main_thread_4=function(){return(Bc=z._emscripten_sync_run_in_main_thread_4=z.asm.sa).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_5=function(){return(z._emscripten_sync_run_in_main_thread_5=z.asm.ta).apply(null,arguments)};z._emscripten_sync_run_in_main_thread_6=function(){return(z._emscripten_sync_run_in_main_thread_6=z.asm.ua).apply(null,arguments)};
z._emscripten_sync_run_in_main_thread_7=function(){return(z._emscripten_sync_run_in_main_thread_7=z.asm.va).apply(null,arguments)};var bc=z._emscripten_run_in_main_runtime_thread_js=function(){return(bc=z._emscripten_run_in_main_runtime_thread_js=z.asm.wa).apply(null,arguments)},ic=z.__emscripten_call_on_thread=function(){return(ic=z.__emscripten_call_on_thread=z.asm.xa).apply(null,arguments)};z._emscripten_tls_init=function(){return(z._emscripten_tls_init=z.asm.ya).apply(null,arguments)};
z.dynCall_jiji=function(){return(z.dynCall_jiji=z.asm.za).apply(null,arguments)};var hb=z._main_thread_futex=140556;z.PThread=S;z.PThread=S;z._pthread_self=vc;z.wasmMemory=h;z.ExitStatus=ua;var Ec;function ua(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function Fc(){Ec||Gc();Ec||(Ta=Fc)};
function Gc(){function a(){if(!Ec&&(Ec=!0,z.calledRun=!0,!Ba)){$a(Oa);D||$a(Pa);oa(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(!D){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var b=z.postRun.shift();Qa.unshift(b)}$a(Qa)}}}if(!(0<P)){if(!D){if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ra();$a(Na)}0<P||(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},
1);a()},1)):a())}}z.run=Gc;if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();D||(noExitRuntime=!0);D?S.vb():Gc();


  return wp2_enc_mt.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = wp2_enc_mt;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return wp2_enc_mt; });
    else if (typeof exports === 'object')
      exports["wp2_enc_mt"] = wp2_enc_mt;
    