
var wp2_enc_mt_simd = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(wp2_enc_mt_simd) {
  wp2_enc_mt_simd = wp2_enc_mt_simd || {};


function aa(){d.buffer!=l&&n(d.buffer);return ba}function p(){d.buffer!=l&&n(d.buffer);return ca}function da(){d.buffer!=l&&n(d.buffer);return ea}function fa(){d.buffer!=l&&n(d.buffer);return ia}function u(){d.buffer!=l&&n(d.buffer);return ja}function w(){d.buffer!=l&&n(d.buffer);return ka}function la(){d.buffer!=l&&n(d.buffer);return ma}function na(){d.buffer!=l&&n(d.buffer);return oa}var y;y||(y=typeof wp2_enc_mt_simd !== 'undefined' ? wp2_enc_mt_simd : {});var pa,qa;
y.ready=new Promise(function(a,b){pa=a;qa=b});var ra={},z;for(z in y)y.hasOwnProperty(z)&&(ra[z]=y[z]);var sa=!1,A=!1,B=!1,ta=!1;sa="object"===typeof window;A="function"===typeof importScripts;B="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ta=!sa&&!B&&!A;var C=y.ENVIRONMENT_IS_PTHREAD||!1;C&&(l=y.buffer,ua=y.DYNAMIC_BASE,va=y.DYNAMICTOP_PTR);var D="";function wa(a){return y.locateFile?y.locateFile(a,D):D+a}var F,G,I,J;
if(B){D=A?require("path").dirname(D)+"/":__dirname+"/";F=function(a,b){I||(I=require("fs"));J||(J=require("path"));a=J.normalize(a);return I.readFileSync(a,b?null:"utf8")};G=function(a){a=F(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof xa))throw a;});process.on("unhandledRejection",K);y.inspect=function(){return"[Emscripten Module object]"};
var za;try{za=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=za.Worker}else if(ta)"undefined"!=typeof read&&(F=function(a){return read(a)}),G=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(sa||A)A?D=self.location.href:document.currentScript&&(D=document.currentScript.src),_scriptDir&&(D=_scriptDir),0!==D.indexOf("blob:")?D=D.substr(0,D.lastIndexOf("/")+1):D="",B?(F=function(a,b){I||(I=require("fs"));J||(J=require("path"));a=J.normalize(a);return I.readFileSync(a,b?null:"utf8")},G=function(a){a=F(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(F=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},A&&(G=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));B&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var Aa=y.print||console.log.bind(console),L=y.printErr||console.warn.bind(console);for(z in ra)ra.hasOwnProperty(z)&&(y[z]=ra[z]);ra=null;var Ba,Ca;y.wasmBinary&&(Ca=y.wasmBinary);var noExitRuntime;
y.noExitRuntime&&(noExitRuntime=y.noExitRuntime);"object"!==typeof WebAssembly&&K("no native wasm support detected");var d,Da=new WebAssembly.Table({initial:433,maximum:433,element:"anyfunc"}),Ea,threadInfoStruct=0,selfThreadId=0,Fa=!1;function assert(a,b){a||K("Assertion failed: "+b)}
function Ga(a,b,c){c=b+c;for(var e="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function M(a,b){return a?Ga(p(),a,b):""}
function Ha(a,b,c){var e=p();if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}
function Ia(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function Ja(a,b){for(var c=0,e="";;){var f=da()[a+2*c>>1];if(0==f||c==b/2)return e;++c;e+=String.fromCharCode(f)}}function Ka(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);da()[b>>1]=g;b+=2}da()[b>>1]=0;return b-e}
function La(a){return 2*a.length}function Ma(a,b){for(var c=0,e="";!(c>=b/4);){var f=u()[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}function Na(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}u()[b>>2]=g;b+=4;if(b+4>c)break}u()[b>>2]=0;return b-e}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var l,ba,ca,ea,ia,ja,ka,ma,oa;function n(a){l=a;y.HEAP8=ba=new Int8Array(a);y.HEAP16=ea=new Int16Array(a);y.HEAP32=ja=new Int32Array(a);y.HEAPU8=ca=new Uint8Array(a);y.HEAPU16=ia=new Uint16Array(a);y.HEAPU32=ka=new Uint32Array(a);y.HEAPF32=ma=new Float32Array(a);y.HEAPF64=oa=new Float64Array(a)}var ua=5384960,va=141152,Pa=y.INITIAL_MEMORY||16777216;
if(C)d=y.wasmMemory,l=y.buffer;else if(y.wasmMemory)d=y.wasmMemory;else if(d=new WebAssembly.Memory({initial:Pa/65536,maximum:32768,shared:!0}),!(d.buffer instanceof SharedArrayBuffer))throw L("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),B&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");d&&(l=d.buffer);Pa=l.byteLength;n(l);C||(u()[va>>2]=ua);function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(y);else{var c=b.Db;"number"===typeof c?void 0===b.fb?y.dynCall_v(c):y.dynCall_vi(c,b.fb):c(void 0===b.fb?null:b.fb)}}}var Ra=[],Sa=[],Ta=[],Ua=[];function Va(){var a=y.preRun.shift();Ra.unshift(a)}var Wa=Math.ceil,Xa=Math.floor,N=0,Ya=null,Za=null;y.preloadedImages={};y.preloadedAudios={};
function K(a){if(y.onAbort)y.onAbort(a);C&&console.error("Pthread aborting at "+Error().stack);L(a);Fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");qa(a);throw a;}function $a(a){var b=P;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function ab(){return $a("data:application/octet-stream;base64,")}var P="wp2_enc_mt_simd.wasm";ab()||(P=wa(P));
function bb(){try{if(Ca)return new Uint8Array(Ca);if(G)return G(P);throw"both async and sync fetching of the wasm failed";}catch(a){K(a)}}function cb(){return Ca||!sa&&!A||"function"!==typeof fetch||$a("file://")?new Promise(function(a){a(bb())}):fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return bb()})}
var eb={126133:function(a,b){setTimeout(function(){db(a,b)},0)},126211:function(){throw"Canceled!";}};C||Sa.push({Db:function(){fb()}});var Q=0,gb=0,hb=0;function ib(a,b,c){Q=a|0;hb=b|0;gb=c|0}y.registerPthreadPtr=ib;
function jb(a,b){if(0>=a||a>aa().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(u(),35516),e=0;if(c==a&&Atomics.compareExchange(u(),35516,c,0)==c&&(--b,e=1,0>=b))return 1;a=Atomics.notify(u(),a>>2,b);if(0<=a)return a+e;throw"Atomics.notify returned an unexpected value "+a;}y._emscripten_futex_wake=jb;
function kb(a){if(C)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";u()[a+12>>2]=0;(a=R.Za[a])&&R.kb(a.worker)}
var R={$b:1,hc:{xb:0,yb:0},Xa:[],ab:[],Lb:function(){ib(R.Va,!A,1);lb(R.Va)},Kb:function(){for(var a=navigator.hardwareConcurrency,b=0;b<a;++b)R.rb();R.Va=141312;for(b=0;58>b;++b)w()[R.Va/4+b]=0;u()[R.Va+12>>2]=R.Va;a=R.Va+156;u()[a>>2]=a;for(b=0;128>b;++b)w()[35388+b]=0;Atomics.store(w(),R.Va+104>>2,141552);Atomics.store(w(),R.Va+40>>2,R.Va);Atomics.store(w(),R.Va+44>>2,42)},Mb:function(){R.receiveObjectTransfer=R.Rb;R.setThreadStatus=R.Sb;R.threadCancel=R.Xb;R.threadExit=R.Yb},Za:{},pb:[],Sb:function(){},
wb:function(){for(;0<R.pb.length;)R.pb.pop()();C&&threadInfoStruct&&mb()},Yb:function(a){var b=Q|0;b&&(Atomics.store(w(),b+4>>2,a),Atomics.store(w(),b+0>>2,1),Atomics.store(w(),b+60>>2,1),Atomics.store(w(),b+64>>2,0),R.wb(),jb(b+0,2147483647),ib(0,0,0),threadInfoStruct=0,C&&postMessage({cmd:"exit"}))},Xb:function(){R.wb();Atomics.store(w(),threadInfoStruct+4>>2,-1);Atomics.store(w(),threadInfoStruct+0>>2,1);jb(threadInfoStruct+0,2147483647);threadInfoStruct=selfThreadId=0;ib(0,0,0);postMessage({cmd:"cancelDone"})},
nc:function(){for(var a in R.Za){var b=R.Za[a];b&&b.worker&&R.kb(b.worker)}R.Za={};for(a=0;a<R.Xa.length;++a){var c=R.Xa[a];c.terminate()}R.Xa=[];for(a=0;a<R.ab.length;++a)c=R.ab[a],b=c.Wa,R.nb(b),c.terminate();R.ab=[]},nb:function(a){if(a){if(a.threadInfoStruct){var b=u()[a.threadInfoStruct+104>>2];u()[a.threadInfoStruct+104>>2]=0;S(b);S(a.threadInfoStruct)}a.threadInfoStruct=0;a.lb&&a.bb&&S(a.bb);a.bb=0;a.worker&&(a.worker.Wa=null)}},kb:function(a){delete R.Za[a.Wa.zb];R.Xa.push(a);R.ab.splice(R.ab.indexOf(a),
1);R.nb(a.Wa);a.Wa=void 0},Rb:function(){},ub:function(a,b){a.onmessage=function(c){var e=c.data,f=e.cmd;a.Wa&&(R.mb=a.Wa.threadInfoStruct);if(e.targetThread&&e.targetThread!=(Q|0)){var g=R.Za[e.mc];g?g.worker.postMessage(c.data,e.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+e.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)nb();else if("spawnThread"===f)ob(c.data);else if("cleanupThread"===f)kb(e.thread);
else if("killThread"===f){c=e.thread;if(C)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";u()[c+12>>2]=0;c=R.Za[c];c.worker.terminate();R.nb(c);R.ab.splice(R.ab.indexOf(c.worker),1);c.worker.Wa=void 0}else if("cancelThread"===f){c=e.thread;if(C)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";
R.Za[c].worker.postMessage({cmd:"cancel"})}else"loaded"===f?(a.loaded=!0,b&&b(a),a.gb&&(a.gb(),delete a.gb)):"print"===f?Aa("Thread "+e.threadId+": "+e.text):"printErr"===f?L("Thread "+e.threadId+": "+e.text):"alert"===f?alert("Thread "+e.threadId+": "+e.text):"exit"===f?a.Wa&&Atomics.load(w(),a.Wa.zb+68>>2)&&R.kb(a):"cancelDone"===f?R.kb(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):L("worker sent an unknown command "+f));R.mb=void 0};a.onerror=function(c){L("pthread sent an error! "+
c.filename+":"+c.lineno+": "+c.message)};B&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){console.log("worker exited - TODO: update the worker queue?")}));a.postMessage({cmd:"load",urlOrBlob:y.mainScriptUrlOrBlob||_scriptDir,wasmMemory:d,wasmModule:Ea,DYNAMIC_BASE:ua,DYNAMICTOP_PTR:va})},rb:function(){var a=wa("wp2_enc_mt_simd.worker.js");R.Xa.push(new Worker(a))},Eb:function(){0==R.Xa.length&&(R.rb(),R.ub(R.Xa[0]));return 0<R.Xa.length?
R.Xa.pop():null},ac:function(a){for(a=performance.now()+a;performance.now()<a;);}};y.establishStackSpace=function(a){pb(a)};y.getNoExitRuntime=function(){return noExitRuntime};var qb;B?qb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:C?qb=function(){return performance.now()-y.__performance_now_clock_drift}:"undefined"!==typeof dateNow?qb=dateNow:qb=function(){return performance.now()};function rb(a,b){R.pb.push(function(){sb(a,b)})}function tb(){return 0<tb.qb}var ub={};
function vb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function wb(a){return this.fromWireType(w()[a>>2])}var T={},U={},xb={};function yb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function zb(a,b){a=yb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ab(a){var b=Error,c=zb(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Bb=void 0;
function Cb(a,b,c){function e(m){m=c(m);if(m.length!==a.length)throw new Bb("Mismatched type converter count");for(var k=0;k<a.length;++k)V(a[k],m[k])}a.forEach(function(m){xb[m]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(m,k){U.hasOwnProperty(m)?f[k]=U[m]:(g.push(m),T.hasOwnProperty(m)||(T[m]=[]),T[m].push(function(){f[k]=U[m];++h;h===g.length&&e(f)}))});0===g.length&&e(f)}
function Db(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Eb=void 0;function W(a){for(var b="";p()[a];)b+=Eb[p()[a++]];return b}var Fb=void 0;function X(a){throw new Fb(a);}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||X('type "'+e+'" must have a positive integer typeid pointer');if(U.hasOwnProperty(a)){if(c.Ib)return;X("Cannot register type '"+e+"' twice")}U[a]=b;delete xb[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(function(f){f()}))}var Gb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Hb(a){4<a&&0===--Y[a].ob&&(Y[a]=void 0,Gb.push(a))}function Ib(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Gb.length?Gb.pop():Y.length;Y[b]={ob:1,value:a};return b}}function Jb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Kb(a,b){switch(b){case 2:return function(c){return this.fromWireType(la()[c>>2])};case 3:return function(c){return this.fromWireType(na()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Lb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=zb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Mb(a,b){var c=y;if(void 0===c[a].Ya){var e=c[a];c[a]=function(){c[a].Ya.hasOwnProperty(arguments.length)||X("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Ya+")!");return c[a].Ya[arguments.length].apply(this,arguments)};c[a].Ya=[];c[a].Ya[e.Ab]=e}}
function Nb(a,b,c){y.hasOwnProperty(a)?((void 0===c||void 0!==y[a].Ya&&void 0!==y[a].Ya[c])&&X("Cannot register public name '"+a+"' twice"),Mb(a,a),y.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),y[a].Ya[c]=b):(y[a]=b,void 0!==c&&(y[a].jc=c))}function Ob(a,b){for(var c=[],e=0;e<a;e++)c.push(u()[(b>>2)+e]);return c}
function Pb(a,b){a=W(a);var c=y["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var Qb=void 0;function Rb(a){a=Sb(a);var b=W(a);S(a);return b}
function Tb(a,b){function c(g){f[g]||U[g]||(xb[g]?xb[g].forEach(c):(e.push(g),f[g]=!0))}var e=[],f={};b.forEach(c);throw new Qb(a+": "+e.map(Rb).join([", "]));}function Ub(a,b,c){switch(b){case 0:return c?function(e){return aa()[e]}:function(e){return p()[e]};case 1:return c?function(e){return da()[e>>1]}:function(e){return fa()[e>>1]};case 2:return c?function(e){return u()[e>>2]}:function(e){return w()[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Vb={};
function Wb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Xb(a,b){var c=U[a];void 0===c&&X(b+" has unknown type "+Rb(a));return c}var Yb={};
function Zb(){B||A||(Ba||(Ba={}),Ba["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ba["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,L("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function $b(a,b,c){if(0>=a||a>aa().length||a&1)return-28;if(A){a=Atomics.wait(u(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+a;}var e=Atomics.load(u(),a>>2);if(b!=e)return-6;b=performance.now();c=b+c;Atomics.store(u(),35516,a);for(e=a;a==e;){b=performance.now();if(b>c)return-73;nb();a=Atomics.load(u(),35516)}return 0}
function ac(a,b){for(var c=arguments.length-2,e=bc(),f=cc(8*c),g=f>>3,h=0;h<c;h++)na()[g+h]=arguments[2+h];c=dc(a,c,f,b);pb(e);return c}var ec=[],fc=[],hc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function ic(a){a=2<a?M(a):a;return hc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function jc(a,b,c){var e=ic(a);if(!e)return-4;e.jb&&(u()[e.jb>>2]=b,u()[e.jb+4>>2]=c);if(e.vb||!e.cc)e.vb&&(e=e.vb),a=!1,e.ib&&e.ib.hb&&(a=e.ib.hb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=c,a&&e.ib.hb.viewport(0,0,b,c);else{if(e.jb){e=u()[e.jb+8>>2];a=a?M(a):"";var f=bc(),g=cc(12),h=0;if(a){h=Ia(a)+1;var m=Z(h);Ha(a,m,h);h=m}u()[g>>2]=h;u()[g+4>>2]=b;u()[g+8>>2]=c;kc(0,e,657457152,0,h,g);pb(f);return 1}return-4}return 0}
function lc(a,b,c){return C?ac(1,1,a,b,c):jc(a,b,c)}function mc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,g){b.drawArraysInstancedANGLE(c,e,f,g)},a.drawElementsInstanced=function(c,e,f,g,h){b.drawElementsInstancedANGLE(c,e,f,g,h)})}
function nc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function oc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function pc(a){a||(a=qc);if(!a.Jb){a.Jb=!0;var b=a.hb;mc(b);nc(b);oc(b);b.dc=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(e){-1!=c.indexOf(e)&&b.getExtension(e)})}}var qc,rc=["default","low-power","high-performance"],sc=[null,[],[]];function tc(a){return C?ac(2,1,a):0}function uc(a,b,c,e,f){if(C)return ac(3,1,a,b,c,e,f)}function vc(a,b,c,e){if(C)return ac(4,1,a,b,c,e);for(var f=0,g=0;g<c;g++){for(var h=u()[b+8*g>>2],m=u()[b+(8*g+4)>>2],k=0;k<m;k++){var r=p()[h+k],q=sc[a];0===r||10===r?((1===a?Aa:L)(Ga(q,0)),q.length=0):q.push(r)}f+=m}u()[e>>2]=f;return 0}
function ob(a){if(C)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=R.Eb();if(void 0!==b.Wa)throw"Internal error!";if(!a.cb)throw"Internal error, no pthread ptr!";R.ab.push(b);for(var c=Z(512),e=0;128>e;++e)u()[c+4*e>>2]=0;var f=a.bb+a.eb;e=R.Za[a.cb]={worker:b,bb:a.bb,eb:a.eb,lb:a.lb,zb:a.cb,threadInfoStruct:a.cb};var g=e.threadInfoStruct>>2;Atomics.store(w(),g,0);Atomics.store(w(),g+1,0);Atomics.store(w(),g+2,0);Atomics.store(w(),g+17,a.detached);
Atomics.store(w(),g+26,c);Atomics.store(w(),g+12,0);Atomics.store(w(),g+10,e.threadInfoStruct);Atomics.store(w(),g+11,42);Atomics.store(w(),g+27,a.eb);Atomics.store(w(),g+21,a.eb);Atomics.store(w(),g+20,f);Atomics.store(w(),g+29,f);Atomics.store(w(),g+30,a.detached);Atomics.store(w(),g+32,a.xb);Atomics.store(w(),g+33,a.yb);c=wc()+40;Atomics.store(w(),g+44,c);b.Wa=e;var h={cmd:"run",start_routine:a.Wb,arg:a.fb,threadInfoStruct:a.cb,selfThreadId:a.cb,parentThreadId:a.Ob,stackBase:a.bb,stackSize:a.eb};
b.gb=function(){h.time=performance.now();b.postMessage(h,a.Zb)};b.loaded&&(b.gb(),delete b.gb)}function xc(){return Q|0}y._pthread_self=xc;
function yc(a,b){if(!a)return L("pthread_join attempted on a null thread pointer!"),71;if(C&&selfThreadId==a)return L("PThread "+a+" is attempting to join to itself!"),16;if(!C&&R.Va==a)return L("Main thread "+a+" is attempting to join to itself!"),16;if(u()[a+12>>2]!==a)return L("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(w(),a+68>>2))return L("Attempted to join thread "+a+", which was already detached!"),28;for(Zb();;){var c=
Atomics.load(w(),a+0>>2);if(1==c)return c=Atomics.load(w(),a+4>>2),b&&(u()[b>>2]=c),Atomics.store(w(),a+68>>2,1),C?postMessage({cmd:"cleanupThread",thread:a}):kb(a),0;if(C&&threadInfoStruct&&!Atomics.load(w(),threadInfoStruct+60>>2)&&2==Atomics.load(w(),threadInfoStruct+0>>2))throw"Canceled!";C||nb();$b(a+0,c,C?100:1)}}C?R.Mb():R.Kb();Bb=y.InternalError=Ab("InternalError");for(var zc=Array(256),Ac=0;256>Ac;++Ac)zc[Ac]=String.fromCharCode(Ac);Eb=zc;Fb=y.BindingError=Ab("BindingError");
y.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};y.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Qb=y.UnboundTypeError=Ab("UnboundTypeError");
var Bc=[null,lc,tc,uc,vc],Ec={g:function(a,b,c,e){K("Assertion failed: "+M(a)+", at: "+[b?M(b):"unknown filename",c,e?M(e):"unknown function"])},R:function(a){return Z(a)},V:function(a,b){return rb(a,b)},Q:function(a){"uncaught_exception"in tb?tb.qb++:tb.qb=1;throw a;},x:function(a){var b=ub[a];delete ub[a];var c=b.Pb,e=b.Qb,f=b.tb,g=f.map(function(h){return h.Hb}).concat(f.map(function(h){return h.Ub}));Cb([a],g,function(h){var m={};f.forEach(function(k,r){var q=h[r],v=k.Fb,x=k.Gb,E=h[r+f.length],
t=k.Tb,ya=k.Vb;m[k.Cb]={read:function(H){return q.fromWireType(v(x,H))},write:function(H,O){var ha=[];t(ya,H,E.toWireType(ha,O));vb(ha)}}});return[{name:b.name,fromWireType:function(k){var r={},q;for(q in m)r[q]=m[q].read(k);e(k);return r},toWireType:function(k,r){for(var q in m)if(!(q in r))throw new TypeError('Missing field:  "'+q+'"');var v=c();for(q in m)m[q].write(v,r[q]);null!==k&&k.push(e,v);return v},argPackAdvance:8,readValueFromPointer:wb,$a:e}]})},O:function(a,b,c,e,f){var g=Db(c);b=W(b);
V(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,m){return m?e:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var m=aa();else if(2===c)m=da();else if(4===c)m=u();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[h>>g])},$a:null})},N:function(a,b){b=W(b);V(a,{name:b,fromWireType:function(c){var e=Y[c].value;Hb(c);return e},toWireType:function(c,e){return Ib(e)},argPackAdvance:8,readValueFromPointer:wb,$a:null})},t:function(a,b,
c){c=Db(c);b=W(b);V(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Jb(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Kb(b,c),$a:null})},w:function(a,b,c,e,f,g){var h=Ob(b,c);a=W(a);f=Pb(e,f);Nb(a,function(){Tb("Cannot call "+a+" due to unbound types",h)},b-1);Cb([],h,function(m){var k=[m[0],null].concat(m.slice(1)),r=m=a,q=f,v=k.length;2>v&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var x=null!==k[1]&&!1,E=!1,t=1;t<k.length;++t)if(null!==k[t]&&void 0===k[t].$a){E=!0;break}var ya="void"!==k[0].name,H="",O="";for(t=0;t<v-2;++t)H+=(0!==t?", ":"")+"arg"+t,O+=(0!==t?", ":"")+"arg"+t+"Wired";r="return function "+yb(r)+"("+H+") {\nif (arguments.length !== "+(v-2)+") {\nthrowBindingError('function "+r+" called with ' + arguments.length + ' arguments, expected "+(v-2)+" args!');\n}\n";E&&(r+="var destructors = [];\n");var ha=E?"destructors":"null";H="throwBindingError invoker fn runDestructors retType classParam".split(" ");
q=[X,q,g,vb,k[0],k[1]];x&&(r+="var thisWired = classParam.toWireType("+ha+", this);\n");for(t=0;t<v-2;++t)r+="var arg"+t+"Wired = argType"+t+".toWireType("+ha+", arg"+t+"); // "+k[t+2].name+"\n",H.push("argType"+t),q.push(k[t+2]);x&&(O="thisWired"+(0<O.length?", ":"")+O);r+=(ya?"var rv = ":"")+"invoker(fn"+(0<O.length?", ":"")+O+");\n";if(E)r+="runDestructors(destructors);\n";else for(t=x?1:2;t<k.length;++t)v=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==k[t].$a&&(r+=v+"_dtor("+v+"); // "+k[t].name+
"\n",H.push(v+"_dtor"),q.push(k[t].$a));ya&&(r+="var ret = retType.fromWireType(rv);\nreturn ret;\n");H.push(r+"}\n");k=Lb(H).apply(null,q);t=b-1;if(!y.hasOwnProperty(m))throw new Bb("Replacing nonexistant public symbol");void 0!==y[m].Ya&&void 0!==t?y[m].Ya[t]=k:(y[m]=k,y[m].Ab=t);return[]})},h:function(a,b,c,e,f){function g(r){return r}b=W(b);-1===f&&(f=4294967295);var h=Db(c);if(0===e){var m=32-8*c;g=function(r){return r<<m>>>m}}var k=-1!=b.indexOf("unsigned");V(a,{name:b,fromWireType:g,toWireType:function(r,
q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Jb(q)+'" to '+this.name);if(q<e||q>f)throw new TypeError('Passing a number "'+Jb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return k?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Ub(b,h,0!==e),$a:null})},f:function(a,b,c){function e(g){g>>=2;var h=w();return new f(l,h[g+1],h[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=W(c);V(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{Ib:!0})},u:function(a,b){b=W(b);var c="std::string"===b;V(a,{name:b,fromWireType:function(e){var f=w()[e>>2];if(c)for(var g=e+4,h=0;h<=f;++h){var m=e+4+h;if(h==f||0==p()[m]){g=M(g,m-g);if(void 0===k)var k=g;else k+=String.fromCharCode(0),k+=g;g=m+1}}else{k=Array(f);for(h=0;h<f;++h)k[h]=String.fromCharCode(p()[e+4+h]);k=k.join("")}S(e);return k},toWireType:function(e,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||X("Cannot pass non-string to std::string");var h=(c&&g?function(){return Ia(f)}:function(){return f.length})(),m=Z(4+h+1);w()[m>>2]=h;if(c&&g)Ha(f,m+4,h+1);else if(g)for(g=0;g<h;++g){var k=f.charCodeAt(g);255<k&&(S(m),X("String has UTF-16 code units that do not fit in 8 bits"));p()[m+4+g]=k}else for(g=0;g<h;++g)p()[m+4+g]=f[g];null!==e&&e.push(S,m);return m},
argPackAdvance:8,readValueFromPointer:wb,$a:function(e){S(e)}})},n:function(a,b,c){c=W(c);if(2===b){var e=Ja;var f=Ka;var g=La;var h=function(){return fa()};var m=1}else 4===b&&(e=Ma,f=Na,g=Oa,h=function(){return w()},m=2);V(a,{name:c,fromWireType:function(k){for(var r=w()[k>>2],q=h(),v,x=k+4,E=0;E<=r;++E){var t=k+4+E*b;if(E==r||0==q[t>>m])x=e(x,t-x),void 0===v?v=x:(v+=String.fromCharCode(0),v+=x),x=t+b}S(k);return v},toWireType:function(k,r){"string"!==typeof r&&X("Cannot pass non-string to C++ string type "+
c);var q=g(r),v=Z(4+q+b);w()[v>>2]=q>>m;f(r,v+4,q+b);null!==k&&k.push(S,v);return v},argPackAdvance:8,readValueFromPointer:wb,$a:function(k){S(k)}})},y:function(a,b,c,e,f,g){ub[a]={name:W(b),Pb:Pb(c,e),Qb:Pb(f,g),tb:[]}},l:function(a,b,c,e,f,g,h,m,k,r){ub[a].tb.push({Cb:W(b),Hb:c,Fb:Pb(e,f),Gb:g,Ub:h,Tb:Pb(m,k),Vb:r})},P:function(a,b){b=W(b);V(a,{fc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},I:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(C)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=R.Za[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},q:Hb,M:function(a){if(0===a)return Ib(Wb());var b=Vb[a];a=void 0===b?W(a):b;return Ib(Wb()[a])},T:function(a){4<a&&(Y[a].ob+=1)},E:function(a,b,c,e){a||X("Cannot use deleted val. handle = "+a);a=Y[a].value;var f=Yb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)h+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(Xb,y,Ib);Yb[b]=f}return f(a,c,e)},r:function(){K()},m:function(a,b,c){fc.length=0;var e;for(c>>=2;e=p()[b++];)(e=105>e)&&c&1&&c++,
fc.push(e?na()[c++>>1]:u()[c]),++c;return eb[a].apply(null,fc)},K:Zb,p:function(){},d:$b,e:jb,a:qb,j:function(){return hb|0},J:function(){return gb|0},C:function(a,b,c){p().copyWithin(a,b,b+c)},U:function(){return navigator.hardwareConcurrency},F:function(a,b,c){ec.length=b;c>>=3;for(var e=0;e<b;e++)ec[e]=na()[c+e];return(0>a?eb[-a-1]:Bc[a]).apply(null,ec)},k:function(a){a>>>=0;var b=p().length;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,
a,e);0<e%65536&&(e+=65536-e%65536);a:{try{d.grow(Math.min(2147483648,e)-l.byteLength+65535>>>16);n(d.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},G:function(a,b,c){return ic(a)?jc(a,b,c):lc(a,b,c)},c:function(){},H:function(a,b){var c={};b>>=2;c.alpha=!!u()[b];c.depth=!!u()[b+1];c.stencil=!!u()[b+2];c.antialias=!!u()[b+3];c.premultipliedAlpha=!!u()[b+4];c.preserveDrawingBuffer=!!u()[b+5];var e=u()[b+6];c.powerPreference=rc[e];c.failIfMajorPerformanceCaveat=!!u()[b+7];c.Nb=u()[b+
8];c.ic=u()[b+9];c.sb=u()[b+10];c.Bb=u()[b+11];c.kc=u()[b+12];c.lc=u()[b+13];(a=ic(a))?c.Bb?c=-1:(a=a.getContext("webgl",c))?(b=Z(8),u()[b+4>>2]=Q|0,e={ec:b,attributes:c,version:c.Nb,hb:a},a.canvas&&(a.canvas.ib=e),("undefined"===typeof c.sb||c.sb)&&pc(e),c=b):c=0:c=-4;return c},L:tc,z:uc,s:vc,B:function(){R.Lb()},memory:d||y.wasmMemory,D:rb,v:function(a,b,c,e){if("undefined"===typeof SharedArrayBuffer)return L("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return L("pthread_create called with a null thread pointer!"),28;var f=[];if(C&&0===f.length)return Cc(687865856,a,b,c,e);var g=0,h=0,m=0,k=0;if(b){var r=u()[b>>2];r+=81920;g=u()[b+8>>2];h=0!==u()[b+12>>2];if(0===u()[b+16>>2]){var q=u()[b+20>>2],v=u()[b+24>>2];m=b+20;k=b+24;var x=R.mb?R.mb:Q|0;if(m||k)if(x)if(u()[x+12>>2]!==x)L("pthread_getschedparam attempted on thread "+x+", which does not point to a valid thread, or does not exist anymore!");else{var E=Atomics.load(w(),x+108+20>>2);x=Atomics.load(w(),
x+108+24>>2);m&&(u()[m>>2]=E);k&&(u()[k>>2]=x)}else L("pthread_getschedparam called with a null thread pointer!");m=u()[b+20>>2];k=u()[b+24>>2];u()[b+20>>2]=q;u()[b+24>>2]=v}else m=u()[b+20>>2],k=u()[b+24>>2]}else r=2097152;(b=0==g)?g=Dc(16,r):(g-=r,assert(0<g));q=Z(232);for(v=0;58>v;++v)w()[(q>>2)+v]=0;u()[a>>2]=q;u()[q+12>>2]=q;a=q+156;u()[a>>2]=a;c={bb:g,eb:r,lb:b,xb:m,yb:k,detached:h,Wb:c,cb:q,Ob:Q|0,fb:e,Zb:f};C?(c.bc="spawnThread",postMessage(c,f)):ob(c);return 0},S:function(a,b){return yc(a,
b)},b:xc,o:function(a){a=+a;return 0<=a?+Xa(a+.5):+Wa(a-.5)},i:function(a){a=+a;return 0<=a?+Xa(a+.5):+Wa(a-.5)},A:function(){},table:Da};
(function(){function a(f,g){y.asm=f.exports;Ea=g;if(!C){var h=R.Xa.length;R.Xa.forEach(function(m){R.ub(m,function(){if(!--h&&(N--,y.monitorRunDependencies&&y.monitorRunDependencies(N),0==N&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za))){var k=Za;Za=null;k()}})})}}function b(f){a(f.instance,f.module)}function c(f){return cb().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){L("failed to asynchronously prepare wasm: "+g);K(g)})}var e={a:Ec};C||(assert(!C,"addRunDependency cannot be used in a pthread worker"),
N++,y.monitorRunDependencies&&y.monitorRunDependencies(N));if(y.instantiateWasm)try{return y.instantiateWasm(e,a)}catch(f){return L("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(Ca||"function"!==typeof WebAssembly.instantiateStreaming||ab()||$a("file://")||"function"!==typeof fetch)return c(b);fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){L("wasm streaming compile failed: "+g);L("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();var fb=y.___wasm_call_ctors=function(){return(fb=y.___wasm_call_ctors=y.asm.W).apply(null,arguments)},Z=y._malloc=function(){return(Z=y._malloc=y.asm.X).apply(null,arguments)},S=y._free=function(){return(S=y._free=y.asm.Y).apply(null,arguments)},Sb=y.___getTypeName=function(){return(Sb=y.___getTypeName=y.asm.Z).apply(null,arguments)};y.___embind_register_native_and_builtin_types=function(){return(y.___embind_register_native_and_builtin_types=y.asm._).apply(null,arguments)};
var wc=y._emscripten_get_global_libc=function(){return(wc=y._emscripten_get_global_libc=y.asm.$).apply(null,arguments)};y.___em_js__initPthreadsJS=function(){return(y.___em_js__initPthreadsJS=y.asm.aa).apply(null,arguments)};
var bc=y.stackSave=function(){return(bc=y.stackSave=y.asm.ba).apply(null,arguments)},pb=y.stackRestore=function(){return(pb=y.stackRestore=y.asm.ca).apply(null,arguments)},cc=y.stackAlloc=function(){return(cc=y.stackAlloc=y.asm.da).apply(null,arguments)},Dc=y._memalign=function(){return(Dc=y._memalign=y.asm.ea).apply(null,arguments)};y._emscripten_main_browser_thread_id=function(){return(y._emscripten_main_browser_thread_id=y.asm.fa).apply(null,arguments)};
var mb=y.___pthread_tsd_run_dtors=function(){return(mb=y.___pthread_tsd_run_dtors=y.asm.ga).apply(null,arguments)},nb=y._emscripten_main_thread_process_queued_calls=function(){return(nb=y._emscripten_main_thread_process_queued_calls=y.asm.ha).apply(null,arguments)};y._emscripten_current_thread_process_queued_calls=function(){return(y._emscripten_current_thread_process_queued_calls=y.asm.ia).apply(null,arguments)};
var lb=y._emscripten_register_main_browser_thread_id=function(){return(lb=y._emscripten_register_main_browser_thread_id=y.asm.ja).apply(null,arguments)},db=y._do_emscripten_dispatch_to_thread=function(){return(db=y._do_emscripten_dispatch_to_thread=y.asm.ka).apply(null,arguments)};y._emscripten_async_run_in_main_thread=function(){return(y._emscripten_async_run_in_main_thread=y.asm.la).apply(null,arguments)};
y._emscripten_sync_run_in_main_thread=function(){return(y._emscripten_sync_run_in_main_thread=y.asm.ma).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_0=function(){return(y._emscripten_sync_run_in_main_thread_0=y.asm.na).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_1=function(){return(y._emscripten_sync_run_in_main_thread_1=y.asm.oa).apply(null,arguments)};
y._emscripten_sync_run_in_main_thread_2=function(){return(y._emscripten_sync_run_in_main_thread_2=y.asm.pa).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_xprintf_varargs=function(){return(y._emscripten_sync_run_in_main_thread_xprintf_varargs=y.asm.qa).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_3=function(){return(y._emscripten_sync_run_in_main_thread_3=y.asm.ra).apply(null,arguments)};
var Cc=y._emscripten_sync_run_in_main_thread_4=function(){return(Cc=y._emscripten_sync_run_in_main_thread_4=y.asm.sa).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_5=function(){return(y._emscripten_sync_run_in_main_thread_5=y.asm.ta).apply(null,arguments)};y._emscripten_sync_run_in_main_thread_6=function(){return(y._emscripten_sync_run_in_main_thread_6=y.asm.ua).apply(null,arguments)};
y._emscripten_sync_run_in_main_thread_7=function(){return(y._emscripten_sync_run_in_main_thread_7=y.asm.va).apply(null,arguments)};var dc=y._emscripten_run_in_main_runtime_thread_js=function(){return(dc=y._emscripten_run_in_main_runtime_thread_js=y.asm.wa).apply(null,arguments)},kc=y.__emscripten_call_on_thread=function(){return(kc=y.__emscripten_call_on_thread=y.asm.xa).apply(null,arguments)};y._emscripten_tls_init=function(){return(y._emscripten_tls_init=y.asm.ya).apply(null,arguments)};
y.dynCall_i=function(){return(y.dynCall_i=y.asm.za).apply(null,arguments)};var sb=y.dynCall_vi=function(){return(sb=y.dynCall_vi=y.asm.Aa).apply(null,arguments)};y.dynCall_fii=function(){return(y.dynCall_fii=y.asm.Ba).apply(null,arguments)};y.dynCall_viif=function(){return(y.dynCall_viif=y.asm.Ca).apply(null,arguments)};y.dynCall_iii=function(){return(y.dynCall_iii=y.asm.Da).apply(null,arguments)};y.dynCall_viii=function(){return(y.dynCall_viii=y.asm.Ea).apply(null,arguments)};
y.dynCall_iiiiii=function(){return(y.dynCall_iiiiii=y.asm.Fa).apply(null,arguments)};y.dynCall_viiiii=function(){return(y.dynCall_viiiii=y.asm.Ga).apply(null,arguments)};y.dynCall_vii=function(){return(y.dynCall_vii=y.asm.Ha).apply(null,arguments)};y.dynCall_viiiiiii=function(){return(y.dynCall_viiiiiii=y.asm.Ia).apply(null,arguments)};y.dynCall_viiiiiiiii=function(){return(y.dynCall_viiiiiiiii=y.asm.Ja).apply(null,arguments)};y.dynCall_ii=function(){return(y.dynCall_ii=y.asm.Ka).apply(null,arguments)};
y.dynCall_viiiiiiii=function(){return(y.dynCall_viiiiiiii=y.asm.La).apply(null,arguments)};y.dynCall_viiiiii=function(){return(y.dynCall_viiiiii=y.asm.Ma).apply(null,arguments)};y.dynCall_viiii=function(){return(y.dynCall_viiii=y.asm.Na).apply(null,arguments)};y.dynCall_iidiiii=function(){return(y.dynCall_iidiiii=y.asm.Oa).apply(null,arguments)};y.dynCall_iiiii=function(){return(y.dynCall_iiiii=y.asm.Pa).apply(null,arguments)};y.dynCall_v=function(){return(y.dynCall_v=y.asm.Qa).apply(null,arguments)};
y.dynCall_fi=function(){return(y.dynCall_fi=y.asm.Ra).apply(null,arguments)};y.dynCall_iiii=function(){return(y.dynCall_iiii=y.asm.Sa).apply(null,arguments)};y.dynCall_iiiiiiiiii=function(){return(y.dynCall_iiiiiiiiii=y.asm.Ta).apply(null,arguments)};y.dynCall_jiji=function(){return(y.dynCall_jiji=y.asm.Ua).apply(null,arguments)};y.PThread=R;y.PThread=R;y._pthread_self=xc;y.wasmMemory=d;y.ExitStatus=xa;var Fc;
function xa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Za=function Gc(){Fc||Hc();Fc||(Za=Gc)};
function Hc(){function a(){if(!Fc&&(Fc=!0,y.calledRun=!0,!Fa)){Qa(Sa);C||Qa(Ta);pa(y);if(y.onRuntimeInitialized)y.onRuntimeInitialized();if(!C){if(y.postRun)for("function"==typeof y.postRun&&(y.postRun=[y.postRun]);y.postRun.length;){var b=y.postRun.shift();Ua.unshift(b)}Qa(Ua)}}}if(!(0<N)){if(!C){if(y.preRun)for("function"==typeof y.preRun&&(y.preRun=[y.preRun]);y.preRun.length;)Va();Qa(Ra)}0<N||(y.setStatus?(y.setStatus("Running..."),setTimeout(function(){setTimeout(function(){y.setStatus("")},
1);a()},1)):a())}}y.run=Hc;if(y.preInit)for("function"==typeof y.preInit&&(y.preInit=[y.preInit]);0<y.preInit.length;)y.preInit.pop()();C||(noExitRuntime=!0);C?(y.___embind_register_native_and_builtin_types(),pa(y)):Hc();


  return wp2_enc_mt_simd.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = wp2_enc_mt_simd;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return wp2_enc_mt_simd; });
    else if (typeof exports === 'object')
      exports["wp2_enc_mt_simd"] = wp2_enc_mt_simd;
    