
var jxl_enc_mt = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(jxl_enc_mt) {
  jxl_enc_mt = jxl_enc_mt || {};


function e(){k.buffer!=m&&u(k.buffer);return aa}function v(){k.buffer!=m&&u(k.buffer);return ba}function ca(){k.buffer!=m&&u(k.buffer);return da}function ea(){k.buffer!=m&&u(k.buffer);return fa}function x(){k.buffer!=m&&u(k.buffer);return ha}function A(){k.buffer!=m&&u(k.buffer);return ia}function ja(){k.buffer!=m&&u(k.buffer);return ka}function la(){k.buffer!=m&&u(k.buffer);return na}var C;C||(C=typeof jxl_enc_mt !== 'undefined' ? jxl_enc_mt : {});var oa,pa;
C.ready=new Promise(function(a,b){oa=a;pa=b});var qa={},D;for(D in C)C.hasOwnProperty(D)&&(qa[D]=C[D]);var ra="./this.program",sa=!1,E=!1,F=!1,ta=!1;sa="object"===typeof window;E="function"===typeof importScripts;F="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ta=!sa&&!F&&!E;var G=C.ENVIRONMENT_IS_PTHREAD||!1;G&&(m=C.buffer);var H="";function ua(a){return C.locateFile?C.locateFile(a,H):H+a}var I,K,L,va;
if(F){H=E?require("path").dirname(H)+"/":__dirname+"/";I=function(a,b){L||(L=require("fs"));va||(va=require("path"));a=va.normalize(a);return L.readFileSync(a,b?null:"utf8")};K=function(a){a=I(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ra=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof wa))throw a;});process.on("unhandledRejection",M);C.inspect=function(){return"[Emscripten Module object]"};
var xa;try{xa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=xa.Worker}else if(ta)"undefined"!=typeof read&&(I=function(a){return read(a)}),K=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(sa||E)E?H=self.location.href:"undefined"!==typeof document&&document.currentScript&&(H=document.currentScript.src),_scriptDir&&(H=_scriptDir),0!==H.indexOf("blob:")?H=H.substr(0,H.lastIndexOf("/")+1):H="",F?(I=function(a,b){L||(L=require("fs"));va||(va=require("path"));a=va.normalize(a);return L.readFileSync(a,b?null:"utf8")},K=function(a){a=I(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(I=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},E&&(K=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));F&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ya=C.print||console.log.bind(console),N=C.printErr||console.warn.bind(console);for(D in qa)qa.hasOwnProperty(D)&&(C[D]=qa[D]);qa=null;C.thisProgram&&(ra=C.thisProgram);var za,Aa;
C.wasmBinary&&(Aa=C.wasmBinary);var noExitRuntime;C.noExitRuntime&&(noExitRuntime=C.noExitRuntime);"object"!==typeof WebAssembly&&M("no native wasm support detected");var k,Ba,threadInfoStruct=0,selfThreadId=0,Ca=!1;function assert(a,b){a||M("Assertion failed: "+b)}
function Da(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function O(a,b){return a?Da(v(),a,b):""}
function Ea(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}function Fa(a,b,c){Ea(a,v(),b,c)}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a,b){for(var c=0,d="";;){var f=ca()[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function Ia(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);ca()[b>>1]=g;b+=2}ca()[b>>1]=0;return b-d}
function Ja(a){return 2*a.length}function Ka(a,b){for(var c=0,d="";!(c>=b/4);){var f=x()[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function La(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}x()[b>>2]=g;b+=4;if(b+4>c)break}x()[b>>2]=0;return b-d}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Na(a,b){e().set(a,b)}var m,aa,ba,da,fa,ha,ia,ka,na;function u(a){m=a;C.HEAP8=aa=new Int8Array(a);C.HEAP16=da=new Int16Array(a);C.HEAP32=ha=new Int32Array(a);C.HEAPU8=ba=new Uint8Array(a);C.HEAPU16=fa=new Uint16Array(a);C.HEAPU32=ia=new Uint32Array(a);C.HEAPF32=ka=new Float32Array(a);C.HEAPF64=na=new Float64Array(a)}var Oa=C.INITIAL_MEMORY||16777216;
if(G)k=C.wasmMemory,m=C.buffer;else if(C.wasmMemory)k=C.wasmMemory;else if(k=new WebAssembly.Memory({initial:Oa/65536,maximum:32768,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw N("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),F&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");k&&(m=k.buffer);Oa=m.byteLength;u(m);var Pa,Qa=[],Ra=[],Sa=[],Ta=[];function Ua(){var a=C.preRun.shift();Qa.unshift(a)}var P=0,Va=null,Wa=null;C.preloadedImages={};C.preloadedAudios={};function M(a){if(C.onAbort)C.onAbort(a);G&&console.error("Pthread aborting at "+Error().stack);N(a);Ca=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");pa(a);throw a;}
function Xa(a){var b=Q;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ya(){return Xa("data:application/octet-stream;base64,")}var Q="jxl_enc_mt.wasm";Ya()||(Q=ua(Q));function Za(){try{if(Aa)return new Uint8Array(Aa);if(K)return K(Q);throw"both async and sync fetching of the wasm failed";}catch(a){M(a)}}
function $a(){return Aa||!sa&&!E||"function"!==typeof fetch||Xa("file://")?Promise.resolve().then(Za):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Za()})}var bb={58949:function(a,b){setTimeout(function(){ab(a,b)},0)},59027:function(){throw"Canceled!";}};
function cb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(C);else{var c=b.Ab;"number"===typeof c?void 0===b.Wa?Pa.get(c)():Pa.get(c)(b.Wa):c(void 0===b.Wa?null:b.Wa)}}}function db(a,b,c){var d;-1!=a.indexOf("j")?d=c&&c.length?C["dynCall_"+a].apply(null,[b].concat(c)):C["dynCall_"+a].call(null,b):d=Pa.get(b).apply(null,c);return d}C.dynCall=db;var R=0,eb=0,fb=0;function gb(a,b,c){R=a|0;fb=b|0;eb=c|0}C.registerPthreadPtr=gb;
function hb(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(x(),S.Sa>>2),d=0;if(c==a&&Atomics.compareExchange(x(),S.Sa>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(x(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}C._emscripten_futex_wake=hb;
function ib(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";x()[a+12>>2]=0;(a=S.Oa[a])&&S.cb(a.worker)}
var S={hc:1,oc:{tb:0,ub:0},Ma:[],Qa:[],Ib:function(){for(var a=navigator.hardwareConcurrency,b=0;b<a;++b)S.mb()},Jb:function(){S.Ka=T(232);for(var a=0;58>a;++a)A()[S.Ka/4+a]=0;x()[S.Ka+12>>2]=S.Ka;a=S.Ka+156;x()[a>>2]=a;var b=T(512);for(a=0;128>a;++a)A()[b/4+a]=0;Atomics.store(A(),S.Ka+104>>2,b);Atomics.store(A(),S.Ka+40>>2,S.Ka);Atomics.store(A(),S.Ka+44>>2,42);S.pb();gb(S.Ka,!E,1);jb(S.Ka)},Kb:function(){S.pb();oa(C);S.receiveObjectTransfer=S.Pb;S.setThreadStatus=S.Qb;S.threadCancel=S.$b;S.threadExit=
S.ac},pb:function(){S.Sa=kb},Oa:{},lb:[],Qb:function(){},sb:function(){for(;0<S.lb.length;)S.lb.pop()();G&&threadInfoStruct&&lb()},ac:function(a){var b=R|0;b&&(Atomics.store(A(),b+4>>2,a),Atomics.store(A(),b+0>>2,1),Atomics.store(A(),b+60>>2,1),Atomics.store(A(),b+64>>2,0),S.sb(),hb(b+0,2147483647),gb(0,0,0),threadInfoStruct=0,G&&postMessage({cmd:"exit"}))},$b:function(){S.sb();Atomics.store(A(),threadInfoStruct+4>>2,-1);Atomics.store(A(),threadInfoStruct+0>>2,1);hb(threadInfoStruct+0,2147483647);
threadInfoStruct=selfThreadId=0;gb(0,0,0);postMessage({cmd:"cancelDone"})},vc:function(){for(var a in S.Oa){var b=S.Oa[a];b&&b.worker&&S.cb(b.worker)}S.Oa={};for(a=0;a<S.Ma.length;++a){var c=S.Ma[a];c.terminate()}S.Ma=[];for(a=0;a<S.Qa.length;++a)c=S.Qa[a],b=c.La,S.jb(b),c.terminate();S.Qa=[]},jb:function(a){if(a){if(a.threadInfoStruct){var b=x()[a.threadInfoStruct+104>>2];x()[a.threadInfoStruct+104>>2]=0;U(b);U(a.threadInfoStruct)}a.threadInfoStruct=0;a.hb&&a.Ra&&U(a.Ra);a.Ra=0;a.worker&&(a.worker.La=
null)}},cb:function(a){delete S.Oa[a.La.vb];S.Ma.push(a);S.Qa.splice(S.Qa.indexOf(a),1);S.jb(a.La);a.La=void 0},Pb:function(){},qb:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.La&&(S.ib=a.La.threadInfoStruct);if(d.targetThread&&d.targetThread!=(R|0)){var g=S.Oa[d.uc];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===
f)mb();else if("spawnThread"===f)nb(c.data);else if("cleanupThread"===f)ib(d.thread);else if("killThread"===f){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";x()[c+12>>2]=0;c=S.Oa[c];c.worker.terminate();S.jb(c);S.Qa.splice(S.Qa.indexOf(c.worker),1);c.worker.La=void 0}else if("cancelThread"===f){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";
if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";S.Oa[c].worker.postMessage({cmd:"cancel"})}else"loaded"===f?(a.loaded=!0,b&&b(a),a.Ya&&(a.Ya(),delete a.Ya)):"print"===f?ya("Thread "+d.threadId+": "+d.text):"printErr"===f?N("Thread "+d.threadId+": "+d.text):"alert"===f?alert("Thread "+d.threadId+": "+d.text):"exit"===f?a.La&&Atomics.load(A(),a.La.vb+68>>2)&&S.cb(a):"cancelDone"===f?S.cb(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):N("worker sent an unknown command "+
f));S.ib=void 0};a.onerror=function(c){N("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};F&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:C.mainScriptUrlOrBlob||_scriptDir,wasmMemory:k,wasmModule:Ba})},mb:function(){var a=ua("jxl_enc_mt.worker.js");S.Ma.push(new Worker(a))},Bb:function(){0==S.Ma.length&&(S.mb(),S.qb(S.Ma[0]));return 0<S.Ma.length?S.Ma.pop():null},ic:function(a){for(a=
performance.now()+a;performance.now()<a;);}};C.establishStackSpace=function(a){ob(a)};C.getNoExitRuntime=function(){return noExitRuntime};var pb;F?pb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:G?pb=function(){return performance.now()-C.__performance_now_clock_drift}:"undefined"!==typeof dateNow?pb=dateNow:pb=function(){return performance.now()};function qb(a,b){S.lb.push(function(){Pa.get(a)(b)})}
function rb(a){this.Xa=a-16;this.Vb=function(b){x()[this.Xa+8>>2]=b};this.Sb=function(b){x()[this.Xa+0>>2]=b};this.Tb=function(){x()[this.Xa+4>>2]=0};this.Rb=function(){var b=0;e()[this.Xa+12>>0]=b};this.Ub=function(){var b=0;e()[this.Xa+13>>0]=b};this.Gb=function(b,c){this.Vb(b);this.Sb(c);this.Tb();this.Rb();this.Ub()}}function sb(){return 0<sb.wb}var tb={};function ub(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function vb(a){return this.fromWireType(A()[a>>2])}var wb={},V={},xb={};
function yb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function zb(a,b){a=yb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ab(a){var b=Error,c=zb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Bb=void 0;
function Cb(a,b,c){function d(p){p=c(p);if(p.length!==a.length)throw new Bb("Mismatched type converter count");for(var n=0;n<a.length;++n)W(a[n],p[n])}a.forEach(function(p){xb[p]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(p,n){V.hasOwnProperty(p)?f[n]=V[p]:(g.push(p),wb.hasOwnProperty(p)||(wb[p]=[]),wb[p].push(function(){f[n]=V[p];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}
function Db(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Eb=void 0;function X(a){for(var b="";v()[a];)b+=Eb[v()[a++]];return b}var Fb=void 0;function Y(a){throw new Fb(a);}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Y('type "'+d+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.Fb)return;Y("Cannot register type '"+d+"' twice")}V[a]=b;delete xb[a];wb.hasOwnProperty(a)&&(b=wb[a],delete wb[a],b.forEach(function(f){f()}))}var Gb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Hb(a){4<a&&0===--Z[a].kb&&(Z[a]=void 0,Gb.push(a))}function Ib(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Gb.length?Gb.pop():Z.length;Z[b]={kb:1,value:a};return b}}function Jb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Kb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja()[c>>2])};case 3:return function(c){return this.fromWireType(la()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Lb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=zb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Mb(a,b){var c=C;if(void 0===c[a].Na){var d=c[a];c[a]=function(){c[a].Na.hasOwnProperty(arguments.length)||Y("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Na+")!");return c[a].Na[arguments.length].apply(this,arguments)};c[a].Na=[];c[a].Na[d.xb]=d}}
function Nb(a,b,c){C.hasOwnProperty(a)?((void 0===c||void 0!==C[a].Na&&void 0!==C[a].Na[c])&&Y("Cannot register public name '"+a+"' twice"),Mb(a,a),C.hasOwnProperty(c)&&Y("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),C[a].Na[c]=b):(C[a]=b,void 0!==c&&(C[a].rc=c))}function Ob(a,b){for(var c=[],d=0;d<a;d++)c.push(x()[(b>>2)+d]);return c}
function Pb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];return db(a,b,c)}}function Qb(a,b){a=X(a);var c=-1!=a.indexOf("j")?Pb(a,b):Pa.get(b);"function"!==typeof c&&Y("unknown function pointer with signature "+a+": "+b);return c}var Rb=void 0;function Sb(a){a=Tb(a);var b=X(a);U(a);return b}
function Ub(a,b){function c(g){f[g]||V[g]||(xb[g]?xb[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Rb(a+": "+d.map(Sb).join([", "]));}function Vb(a,b,c){switch(b){case 0:return c?function(d){return e()[d]}:function(d){return v()[d]};case 1:return c?function(d){return ca()[d>>1]}:function(d){return ea()[d>>1]};case 2:return c?function(d){return x()[d>>2]}:function(d){return A()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Wb={};
function Xb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Yb(a,b){var c=V[a];void 0===c&&Y(b+" has unknown type "+Sb(a));return c}var Zb={};
function $b(){F||E||(za||(za={}),za["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(za["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,N("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function ac(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(sa){if(Atomics.load(x(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(x(),S.Sa>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(x(),S.Sa>>2,0),-73;d=Atomics.exchange(x(),S.Sa>>2,0);if(0==d)break;mb();if(Atomics.load(x(),a>>2)!=b)return-6;Atomics.exchange(x(),S.Sa>>2,a)}return 0}a=Atomics.wait(x(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function bc(a,b){for(var c=arguments.length-2,d=cc(),f=dc(8*c),g=f>>3,l=0;l<c;l++)la()[g+l]=arguments[2+l];c=ec(a,c,f,b);ob(d);return c}var fc=[],hc=[],ic=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function jc(a){a=2<a?O(a):a;return ic[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function kc(a,b,c){var d=jc(a);if(!d)return-4;d.bb&&(x()[d.bb>>2]=b,x()[d.bb+4>>2]=c);if(d.rb||!d.kc)d.rb&&(d=d.rb),a=!1,d.ab&&d.ab.$a&&(a=d.ab.$a.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.ab.$a.viewport(0,0,b,c);else{if(d.bb){d=x()[d.bb+8>>2];a=a?O(a):"";var f=cc(),g=dc(12),l=0;if(a){l=Ga(a)+1;var p=T(l);Fa(a,p,l);l=p}x()[g>>2]=l;x()[g+4>>2]=b;x()[g+8>>2]=c;lc(0,d,657457152,0,l,g);ob(f);return 1}return-4}return 0}
function mc(a,b,c){return G?bc(2,1,a,b,c):kc(a,b,c)}function nc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,l){b.drawElementsInstancedANGLE(c,d,f,g,l)})}
function oc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function pc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function qc(a){a||(a=rc);if(!a.Hb){a.Hb=!0;var b=a.$a;nc(b);oc(b);pc(b);b.lc=b.getExtension("EXT_disjoint_timer_query");b.qc=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var rc,sc=["default","low-power","high-performance"],tc={};function uc(){if(!vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ra||"./this.program"},b;for(b in tc)a[b]=tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);vc=c}return vc}var vc,wc=[null,[],[]];
function xc(a){return G?bc(3,1,a):0}function yc(a,b,c,d,f){if(G)return bc(4,1,a,b,c,d,f)}function zc(a,b,c,d){if(G)return bc(5,1,a,b,c,d);for(var f=0,g=0;g<c;g++){for(var l=x()[b+8*g>>2],p=x()[b+(8*g+4)>>2],n=0;n<p;n++){var t=v()[l+n],r=wc[a];0===t||10===t?((1===a?ya:N)(Da(r,0)),r.length=0):r.push(t)}f+=p}x()[d>>2]=f;return 0}
function nb(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=S.Bb();if(void 0!==b.La)throw"Internal error!";if(!a.Ta)throw"Internal error, no pthread ptr!";S.Qa.push(b);for(var c=T(512),d=0;128>d;++d)x()[c+4*d>>2]=0;var f=a.Ra+a.Ua;d=S.Oa[a.Ta]={worker:b,Ra:a.Ra,Ua:a.Ua,hb:a.hb,vb:a.Ta,threadInfoStruct:a.Ta};var g=d.threadInfoStruct>>2;Atomics.store(A(),g,0);Atomics.store(A(),g+1,0);Atomics.store(A(),g+2,0);Atomics.store(A(),g+17,a.detached);
Atomics.store(A(),g+26,c);Atomics.store(A(),g+12,0);Atomics.store(A(),g+10,d.threadInfoStruct);Atomics.store(A(),g+11,42);Atomics.store(A(),g+27,a.Ua);Atomics.store(A(),g+21,a.Ua);Atomics.store(A(),g+20,f);Atomics.store(A(),g+29,f);Atomics.store(A(),g+30,a.detached);Atomics.store(A(),g+32,a.tb);Atomics.store(A(),g+33,a.ub);c=Ac()+40;Atomics.store(A(),g+44,c);b.La=d;var l={cmd:"run",start_routine:a.Zb,arg:a.Wa,threadInfoStruct:a.Ta,selfThreadId:a.Ta,parentThreadId:a.Mb,stackBase:a.Ra,stackSize:a.Ua};
b.Ya=function(){l.time=performance.now();b.postMessage(l,a.fc)};b.loaded&&(b.Ya(),delete b.Ya)}function Bc(){return R|0}C._pthread_self=Bc;
function Cc(a,b){if(!a)return N("pthread_join attempted on a null thread pointer!"),71;if(G&&selfThreadId==a)return N("PThread "+a+" is attempting to join to itself!"),16;if(!G&&S.Ka==a)return N("Main thread "+a+" is attempting to join to itself!"),16;if(x()[a+12>>2]!==a)return N("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(A(),a+68>>2))return N("Attempted to join thread "+a+", which was already detached!"),28;for($b();;){var c=
Atomics.load(A(),a+0>>2);if(1==c)return c=Atomics.load(A(),a+4>>2),b&&(x()[b>>2]=c),Atomics.store(A(),a+68>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):ib(a),0;if(G&&threadInfoStruct&&!Atomics.load(A(),threadInfoStruct+60>>2)&&2==Atomics.load(A(),threadInfoStruct+0>>2))throw"Canceled!";G||mb();ac(a+0,c,G?100:1)}}function Dc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ec(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Fc=[31,29,31,30,31,30,31,31,30,31,30,31],Gc=[31,28,31,30,31,30,31,31,30,31,30,31];function Hc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Dc(a.getFullYear())?Fc:Gc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ic(a,b,c,d){function f(h,q,y){for(h="number"===typeof h?h.toString():h||"";h.length<q;)h=y[0]+h;return h}function g(h,q){return f(h,q,"0")}function l(h,q){function y(J){return 0>J?-1:0<J?1:0}var B;0===(B=y(h.getFullYear()-q.getFullYear()))&&0===(B=y(h.getMonth()-q.getMonth()))&&(B=y(h.getDate()-q.getDate()));return B}function p(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=Hc(new Date(h.Ja+1900,0,1),h.gb);var q=new Date(h.getFullYear()+1,0,4),y=p(new Date(h.getFullYear(),0,4));q=p(q);return 0>=l(y,h)?0>=l(q,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var t=x()[d+40>>2];d={dc:x()[d>>2],cc:x()[d+4>>2],eb:x()[d+8>>2],Za:x()[d+12>>2],Va:x()[d+16>>2],Ja:x()[d+20>>2],fb:x()[d+24>>2],gb:x()[d+28>>2],wc:x()[d+
32>>2],bc:x()[d+36>>2],ec:t?O(t):""};c=O(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
z="January February March April May June July August September October November December".split(" ");t={"%a":function(h){return w[h.fb].substring(0,3)},"%A":function(h){return w[h.fb]},"%b":function(h){return z[h.Va].substring(0,3)},"%B":function(h){return z[h.Va]},"%C":function(h){return g((h.Ja+1900)/100|0,2)},"%d":function(h){return g(h.Za,2)},"%e":function(h){return f(h.Za,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.eb,
2)},"%I":function(h){h=h.eb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Za+Ec(Dc(h.Ja+1900)?Fc:Gc,h.Va-1),3)},"%m":function(h){return g(h.Va+1,2)},"%M":function(h){return g(h.cc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.eb&&12>h.eb?"AM":"PM"},"%S":function(h){return g(h.dc,2)},"%t":function(){return"\t"},"%u":function(h){return h.fb||7},"%U":function(h){var q=new Date(h.Ja+1900,0,1),y=0===q.getDay()?q:Hc(q,7-q.getDay());h=new Date(h.Ja+1900,h.Va,h.Za);return 0>
l(y,h)?g(Math.ceil((31-y.getDate()+(Ec(Dc(h.getFullYear())?Fc:Gc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(y,q)?"01":"00"},"%V":function(h){var q=new Date(h.Ja+1901,0,4),y=p(new Date(h.Ja+1900,0,4));q=p(q);var B=Hc(new Date(h.Ja+1900,0,1),h.gb);return 0>l(B,y)?"53":0>=l(q,B)?"01":g(Math.ceil((y.getFullYear()<h.Ja+1900?h.gb+32-y.getDate():h.gb+1-y.getDate())/7),2)},"%w":function(h){return h.fb},"%W":function(h){var q=new Date(h.Ja,0,1),y=1===q.getDay()?q:Hc(q,0===q.getDay()?1:7-q.getDay()+1);h=
new Date(h.Ja+1900,h.Va,h.Za);return 0>l(y,h)?g(Math.ceil((31-y.getDate()+(Ec(Dc(h.getFullYear())?Fc:Gc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(y,q)?"01":"00"},"%y":function(h){return(h.Ja+1900).toString().substring(2)},"%Y":function(h){return h.Ja+1900},"%z":function(h){h=h.bc;var q=0<=h;h=Math.abs(h)/60;return(q?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ec},"%%":function(){return"%"}};for(r in t)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=
Jc(c);if(r.length>b)return 0;Na(r,a);return r.length-1}
function Kc(a){if(G)return bc(6,1,a);switch(a){case 30:return 16384;case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;
case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===
typeof navigator?navigator.hardwareConcurrency||1:1}x()[Lc()>>2]=28;return-1}G||S.Ib();Bb=C.InternalError=Ab("InternalError");for(var Mc=Array(256),Nc=0;256>Nc;++Nc)Mc[Nc]=String.fromCharCode(Nc);Eb=Mc;Fb=C.BindingError=Ab("BindingError");C.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};C.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};Rb=C.UnboundTypeError=Ab("UnboundTypeError");
var Oc=[null,function(a,b){if(G)return bc(1,1,a,b)},mc,xc,yc,zc,Kc];function Jc(a){var b=Array(Ga(a)+1);Ea(a,b,0,b.length);return b}G||Ra.push({Ab:function(){Pc()}});
var Sc={i:function(a,b,c,d){M("Assertion failed: "+O(a)+", at: "+[b?O(b):"unknown filename",c,d?O(d):"unknown function"])},K:function(a){return T(a+16)+16},X:function(a,b){return qb(a,b)},I:function(a,b,c){(new rb(a)).Gb(b,c);"uncaught_exception"in sb?sb.wb++:sb.wb=1;throw a;},w:function(a){var b=tb[a];delete tb[a];var c=b.Nb,d=b.Ob,f=b.ob,g=f.map(function(l){return l.Eb}).concat(f.map(function(l){return l.Xb}));Cb([a],g,function(l){var p={};f.forEach(function(n,t){var r=l[t],w=n.Cb,z=n.Db,h=l[t+
f.length],q=n.Wb,y=n.Yb;p[n.zb]={read:function(B){return r.fromWireType(w(z,B))},write:function(B,J){var ma=[];q(y,B,h.toWireType(ma,J));ub(ma)}}});return[{name:b.name,fromWireType:function(n){var t={},r;for(r in p)t[r]=p[r].read(n);d(n);return t},toWireType:function(n,t){for(var r in p)if(!(r in t))throw new TypeError('Missing field:  "'+r+'"');var w=c();for(r in p)p[r].write(w,t[r]);null!==n&&n.push(d,w);return w},argPackAdvance:8,readValueFromPointer:vb,Pa:d}]})},S:function(a,b,c,d,f){var g=Db(c);
b=X(b);W(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,p){return p?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var p=e();else if(2===c)p=ca();else if(4===c)p=x();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(p[l>>g])},Pa:null})},R:function(a,b){b=X(b);W(a,{name:b,fromWireType:function(c){var d=Z[c].value;Hb(c);return d},toWireType:function(c,d){return Ib(d)},argPackAdvance:8,readValueFromPointer:vb,Pa:null})},t:function(a,
b,c){c=Db(c);b=X(b);W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Jb(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Kb(b,c),Pa:null})},v:function(a,b,c,d,f,g){var l=Ob(b,c);a=X(a);f=Qb(d,f);Nb(a,function(){Ub("Cannot call "+a+" due to unbound types",l)},b-1);Cb([],l,function(p){var n=[p[0],null].concat(p.slice(1)),t=p=a,r=f,w=n.length;2>w&&Y("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var z=null!==n[1]&&!1,h=!1,q=1;q<n.length;++q)if(null!==n[q]&&void 0===n[q].Pa){h=!0;break}var y="void"!==n[0].name,B="",J="";for(q=0;q<w-2;++q)B+=(0!==q?", ":"")+"arg"+q,J+=(0!==q?", ":"")+"arg"+q+"Wired";t="return function "+yb(t)+"("+B+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+t+" called with ' + arguments.length + ' arguments, expected "+(w-2)+" args!');\n}\n";h&&(t+="var destructors = [];\n");var ma=h?"destructors":"null";B="throwBindingError invoker fn runDestructors retType classParam".split(" ");
r=[Y,r,g,ub,n[0],n[1]];z&&(t+="var thisWired = classParam.toWireType("+ma+", this);\n");for(q=0;q<w-2;++q)t+="var arg"+q+"Wired = argType"+q+".toWireType("+ma+", arg"+q+"); // "+n[q+2].name+"\n",B.push("argType"+q),r.push(n[q+2]);z&&(J="thisWired"+(0<J.length?", ":"")+J);t+=(y?"var rv = ":"")+"invoker(fn"+(0<J.length?", ":"")+J+");\n";if(h)t+="runDestructors(destructors);\n";else for(q=z?1:2;q<n.length;++q)w=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==n[q].Pa&&(t+=w+"_dtor("+w+"); // "+n[q].name+
"\n",B.push(w+"_dtor"),r.push(n[q].Pa));y&&(t+="var ret = retType.fromWireType(rv);\nreturn ret;\n");B.push(t+"}\n");n=Lb(B).apply(null,r);q=b-1;if(!C.hasOwnProperty(p))throw new Bb("Replacing nonexistant public symbol");void 0!==C[p].Na&&void 0!==q?C[p].Na[q]=n:(C[p]=n,C[p].xb=q);return[]})},j:function(a,b,c,d,f){function g(t){return t}b=X(b);-1===f&&(f=4294967295);var l=Db(c);if(0===d){var p=32-8*c;g=function(t){return t<<p>>>p}}var n=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(t,
r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+Jb(r)+'" to '+this.name);if(r<d||r>f)throw new TypeError('Passing a number "'+Jb(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return n?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:Vb(b,l,0!==d),Pa:null})},h:function(a,b,c){function d(g){g>>=2;var l=A();return new f(m,l[g+1],l[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=X(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Fb:!0})},u:function(a,b){b=X(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=A()[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var p=d+4+l;if(l==f||0==v()[p]){g=O(g,p-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=p+1}}else{n=Array(f);for(l=0;l<f;++l)n[l]=String.fromCharCode(v()[d+4+l]);n=n.join("")}U(d);return n},toWireType:function(d,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||Y("Cannot pass non-string to std::string");var l=(c&&g?function(){return Ga(f)}:function(){return f.length})(),p=T(4+l+1);A()[p>>2]=l;if(c&&g)Fa(f,p+4,l+1);else if(g)for(g=0;g<l;++g){var n=f.charCodeAt(g);255<n&&(U(p),Y("String has UTF-16 code units that do not fit in 8 bits"));v()[p+4+g]=n}else for(g=0;g<l;++g)v()[p+4+g]=f[g];null!==d&&d.push(U,p);return p},
argPackAdvance:8,readValueFromPointer:vb,Pa:function(d){U(d)}})},p:function(a,b,c){c=X(c);if(2===b){var d=Ha;var f=Ia;var g=Ja;var l=function(){return ea()};var p=1}else 4===b&&(d=Ka,f=La,g=Ma,l=function(){return A()},p=2);W(a,{name:c,fromWireType:function(n){for(var t=A()[n>>2],r=l(),w,z=n+4,h=0;h<=t;++h){var q=n+4+h*b;if(h==t||0==r[q>>p])z=d(z,q-z),void 0===w?w=z:(w+=String.fromCharCode(0),w+=z),z=q+b}U(n);return w},toWireType:function(n,t){"string"!==typeof t&&Y("Cannot pass non-string to C++ string type "+
c);var r=g(t),w=T(4+r+b);A()[w>>2]=r>>p;f(t,w+4,r+b);null!==n&&n.push(U,w);return w},argPackAdvance:8,readValueFromPointer:vb,Pa:function(n){U(n)}})},x:function(a,b,c,d,f,g){tb[a]={name:X(b),Nb:Qb(c,d),Ob:Qb(f,g),ob:[]}},q:function(a,b,c,d,f,g,l,p,n,t){tb[a].ob.push({zb:X(b),Eb:c,Cb:Qb(d,f),Db:g,Xb:l,Wb:Qb(p,n),Yb:t})},T:function(a,b){b=X(b);W(a,{nc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},H:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=S.Oa[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},l:Hb,W:function(a){if(0===a)return Ib(Xb());var b=Wb[a];a=void 0===b?X(a):b;return Ib(Xb()[a])},V:function(a){4<a&&(Z[a].kb+=1)},y:function(a,b,c,d){a||Y("Cannot use deleted val. handle = "+a);a=Z[a].value;var f=Zb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)l+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",l+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(Yb,C,Ib);Zb[b]=f}return f(a,c,d)},b:function(){M()},m:function(a,b,c){hc.length=0;var d;for(c>>=2;d=v()[b++];)(d=105>d)&&c&1&&c++,
hc.push(d?la()[c++>>1]:x()[c]),++c;return bb[a].apply(null,hc)},J:$b,r:function(){},f:ac,g:hb,d:pb,o:function(){return fb|0},n:function(){return eb|0},C:function(a,b,c){v().copyWithin(a,b,b+c)},E:function(a,b,c){fc.length=b;c>>=3;for(var d=0;d<b;d++)fc[d]=la()[c+d];return(0>a?bb[-a-1]:Oc[a]).apply(null,fc)},k:function(a){a>>>=0;var b=v().length;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{k.grow(Math.min(2147483648,
d)-m.byteLength+65535>>>16);u(k.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},F:function(a,b,c){return jc(a)?kc(a,b,c):mc(a,b,c)},e:function(){},G:function(a,b){var c={};b>>=2;c.alpha=!!x()[b];c.depth=!!x()[b+1];c.stencil=!!x()[b+2];c.antialias=!!x()[b+3];c.premultipliedAlpha=!!x()[b+4];c.preserveDrawingBuffer=!!x()[b+5];var d=x()[b+6];c.powerPreference=sc[d];c.failIfMajorPerformanceCaveat=!!x()[b+7];c.Lb=x()[b+8];c.pc=x()[b+9];c.nb=x()[b+10];c.yb=x()[b+11];c.sc=x()[b+12];c.tc=
x()[b+13];a=jc(a);!a||c.yb?c=0:(a=a.getContext("webgl",c))?(b=T(8),x()[b+4>>2]=R|0,d={mc:b,attributes:c,version:c.Lb,$a:a},a.canvas&&(a.canvas.ab=d),("undefined"===typeof c.nb||c.nb)&&qc(d),c=b):c=0;return c},O:function(a,b){var c=0;uc().forEach(function(d,f){var g=b+c;f=x()[a+4*f>>2]=g;for(g=0;g<d.length;++g)e()[f++>>0]=d.charCodeAt(g);e()[f>>0]=0;c+=d.length+1});return 0},P:function(a,b){var c=uc();x()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});x()[b>>2]=d;return 0},Q:xc,z:yc,
s:zc,B:function(){S.Jb()},a:k||C.wasmMemory,D:qb,U:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return N("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return N("pthread_create called with a null thread pointer!"),28;var f=[];if(G&&0===f.length)return Qc(687865856,a,b,c,d);var g=0,l=0,p=0,n=0;if(b){var t=x()[b>>2];t+=81920;g=x()[b+8>>2];l=0!==x()[b+12>>2];if(0===x()[b+16>>2]){var r=x()[b+20>>2],w=x()[b+24>>2];p=b+20;n=b+24;var z=S.ib?
S.ib:R|0;if(p||n)if(z)if(x()[z+12>>2]!==z)N("pthread_getschedparam attempted on thread "+z+", which does not point to a valid thread, or does not exist anymore!");else{var h=Atomics.load(A(),z+108+20>>2);z=Atomics.load(A(),z+108+24>>2);p&&(x()[p>>2]=h);n&&(x()[n>>2]=z)}else N("pthread_getschedparam called with a null thread pointer!");p=x()[b+20>>2];n=x()[b+24>>2];x()[b+20>>2]=r;x()[b+24>>2]=w}else p=x()[b+20>>2],n=x()[b+24>>2]}else t=2097152;(b=0==g)?g=Rc(16,t):(g-=t,assert(0<g));r=T(232);for(w=
0;58>w;++w)A()[(r>>2)+w]=0;x()[a>>2]=r;x()[r+12>>2]=r;a=r+156;x()[a>>2]=a;c={Ra:g,Ua:t,hb:b,tb:p,ub:n,detached:l,Zb:c,Ta:r,Mb:R|0,Wa:d,fc:f};G?(c.jc="spawnThread",postMessage(c,f)):nb(c);return 0},L:function(a,b){return Cc(a,b)},c:Bc,A:function(){},N:function(a,b,c,d){return Ic(a,b,c,d)},M:Kc};
(function(){function a(f,g){C.asm=f.exports;Pa=C.asm.Y;Ba=g;if(!G){var l=S.Ma.length;S.Ma.forEach(function(p){S.qb(p,function(){if(!--l&&(P--,C.monitorRunDependencies&&C.monitorRunDependencies(P),0==P&&(null!==Va&&(clearInterval(Va),Va=null),Wa))){var n=Wa;Wa=null;n()}})})}}function b(f){a(f.instance,f.module)}function c(f){return $a().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){N("failed to asynchronously prepare wasm: "+g);M(g)})}var d={a:Sc};G||(assert(!G,"addRunDependency cannot be used in a pthread worker"),
P++,C.monitorRunDependencies&&C.monitorRunDependencies(P));if(C.instantiateWasm)try{return C.instantiateWasm(d,a)}catch(f){return N("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Aa||"function"!==typeof WebAssembly.instantiateStreaming||Ya()||Xa("file://")||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){N("wasm streaming compile failed: "+g);N("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(pa);return{}})();var Pc=C.___wasm_call_ctors=function(){return(Pc=C.___wasm_call_ctors=C.asm.Z).apply(null,arguments)},T=C._malloc=function(){return(T=C._malloc=C.asm._).apply(null,arguments)},U=C._free=function(){return(U=C._free=C.asm.$).apply(null,arguments)},Lc=C.___errno_location=function(){return(Lc=C.___errno_location=C.asm.aa).apply(null,arguments)},Tb=C.___getTypeName=function(){return(Tb=C.___getTypeName=C.asm.ba).apply(null,arguments)};
C.___embind_register_native_and_builtin_types=function(){return(C.___embind_register_native_and_builtin_types=C.asm.ca).apply(null,arguments)};var Ac=C._emscripten_get_global_libc=function(){return(Ac=C._emscripten_get_global_libc=C.asm.da).apply(null,arguments)};C.___em_js__initPthreadsJS=function(){return(C.___em_js__initPthreadsJS=C.asm.ea).apply(null,arguments)};
var cc=C.stackSave=function(){return(cc=C.stackSave=C.asm.fa).apply(null,arguments)},ob=C.stackRestore=function(){return(ob=C.stackRestore=C.asm.ga).apply(null,arguments)},dc=C.stackAlloc=function(){return(dc=C.stackAlloc=C.asm.ha).apply(null,arguments)},Rc=C._memalign=function(){return(Rc=C._memalign=C.asm.ia).apply(null,arguments)};C._emscripten_main_browser_thread_id=function(){return(C._emscripten_main_browser_thread_id=C.asm.ja).apply(null,arguments)};
var lb=C.___pthread_tsd_run_dtors=function(){return(lb=C.___pthread_tsd_run_dtors=C.asm.ka).apply(null,arguments)},mb=C._emscripten_main_thread_process_queued_calls=function(){return(mb=C._emscripten_main_thread_process_queued_calls=C.asm.la).apply(null,arguments)};C._emscripten_current_thread_process_queued_calls=function(){return(C._emscripten_current_thread_process_queued_calls=C.asm.ma).apply(null,arguments)};
var jb=C._emscripten_register_main_browser_thread_id=function(){return(jb=C._emscripten_register_main_browser_thread_id=C.asm.na).apply(null,arguments)},ab=C._do_emscripten_dispatch_to_thread=function(){return(ab=C._do_emscripten_dispatch_to_thread=C.asm.oa).apply(null,arguments)};C._emscripten_async_run_in_main_thread=function(){return(C._emscripten_async_run_in_main_thread=C.asm.pa).apply(null,arguments)};
C._emscripten_sync_run_in_main_thread=function(){return(C._emscripten_sync_run_in_main_thread=C.asm.qa).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_0=function(){return(C._emscripten_sync_run_in_main_thread_0=C.asm.ra).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_1=function(){return(C._emscripten_sync_run_in_main_thread_1=C.asm.sa).apply(null,arguments)};
C._emscripten_sync_run_in_main_thread_2=function(){return(C._emscripten_sync_run_in_main_thread_2=C.asm.ta).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_xprintf_varargs=function(){return(C._emscripten_sync_run_in_main_thread_xprintf_varargs=C.asm.ua).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_3=function(){return(C._emscripten_sync_run_in_main_thread_3=C.asm.va).apply(null,arguments)};
var Qc=C._emscripten_sync_run_in_main_thread_4=function(){return(Qc=C._emscripten_sync_run_in_main_thread_4=C.asm.wa).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_5=function(){return(C._emscripten_sync_run_in_main_thread_5=C.asm.xa).apply(null,arguments)};C._emscripten_sync_run_in_main_thread_6=function(){return(C._emscripten_sync_run_in_main_thread_6=C.asm.ya).apply(null,arguments)};
C._emscripten_sync_run_in_main_thread_7=function(){return(C._emscripten_sync_run_in_main_thread_7=C.asm.za).apply(null,arguments)};var ec=C._emscripten_run_in_main_runtime_thread_js=function(){return(ec=C._emscripten_run_in_main_runtime_thread_js=C.asm.Aa).apply(null,arguments)},lc=C.__emscripten_call_on_thread=function(){return(lc=C.__emscripten_call_on_thread=C.asm.Ba).apply(null,arguments)};C._emscripten_tls_init=function(){return(C._emscripten_tls_init=C.asm.Ca).apply(null,arguments)};
C.dynCall_viijii=function(){return(C.dynCall_viijii=C.asm.Da).apply(null,arguments)};C.dynCall_iiji=function(){return(C.dynCall_iiji=C.asm.Ea).apply(null,arguments)};C.dynCall_jiji=function(){return(C.dynCall_jiji=C.asm.Fa).apply(null,arguments)};C.dynCall_iiiiiijj=function(){return(C.dynCall_iiiiiijj=C.asm.Ga).apply(null,arguments)};C.dynCall_iiiiij=function(){return(C.dynCall_iiiiij=C.asm.Ha).apply(null,arguments)};C.dynCall_iiiiijj=function(){return(C.dynCall_iiiiijj=C.asm.Ia).apply(null,arguments)};
var kb=C._main_thread_futex=3066856;C.PThread=S;C.PThread=S;C._pthread_self=Bc;C.wasmMemory=k;C.ExitStatus=wa;var Tc;function wa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Wa=function Uc(){Tc||Vc();Tc||(Wa=Uc)};
function Vc(){function a(){if(!Tc&&(Tc=!0,C.calledRun=!0,!Ca)){cb(Ra);G||cb(Sa);oa(C);if(C.onRuntimeInitialized)C.onRuntimeInitialized();if(!G){if(C.postRun)for("function"==typeof C.postRun&&(C.postRun=[C.postRun]);C.postRun.length;){var b=C.postRun.shift();Ta.unshift(b)}cb(Ta)}}}if(!(0<P)){if(!G){if(C.preRun)for("function"==typeof C.preRun&&(C.preRun=[C.preRun]);C.preRun.length;)Ua();cb(Qa)}0<P||(C.setStatus?(C.setStatus("Running..."),setTimeout(function(){setTimeout(function(){C.setStatus("")},
1);a()},1)):a())}}C.run=Vc;if(C.preInit)for("function"==typeof C.preInit&&(C.preInit=[C.preInit]);0<C.preInit.length;)C.preInit.pop()();G||(noExitRuntime=!0);G?S.Kb():Vc();


  return jxl_enc_mt.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = jxl_enc_mt;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return jxl_enc_mt; });
    else if (typeof exports === 'object')
      exports["jxl_enc_mt"] = jxl_enc_mt;
    