
var jxl_enc = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(jxl_enc) {
  jxl_enc = jxl_enc || {};


var h;h||(h=typeof jxl_enc !== 'undefined' ? jxl_enc : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var t={},w;for(w in h)h.hasOwnProperty(w)&&(t[w]=h[w]);var ca="./this.program",y=!1,z=!1,da=!1,ea=!1;y="object"===typeof window;z="function"===typeof importScripts;da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!y&&!da&&!z;var A="",fa,B,ha,ia;
if(da)A=z?require("path").dirname(A)+"/":__dirname+"/",fa=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},B=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",D),h.inspect=function(){return"[Emscripten Module object]"};else if(ea)"undefined"!=
typeof read&&(fa=function(a){return read(a)}),B=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(y||z)z?A=self.location.href:"undefined"!==typeof document&&document.currentScript&&(A=document.currentScript.src),_scriptDir&&(A=_scriptDir),0!==
A.indexOf("blob:")?A=A.substr(0,A.lastIndexOf("/")+1):A="",fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(B=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ja=h.print||console.log.bind(console),E=h.printErr||console.warn.bind(console);for(w in t)t.hasOwnProperty(w)&&(h[w]=t[w]);t=null;h.thisProgram&&(ca=h.thisProgram);var F;h.wasmBinary&&(F=h.wasmBinary);var noExitRuntime;
h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);"object"!==typeof WebAssembly&&D("no native wasm support detected");var G,ka=!1;function assert(a,b){a||D("Assertion failed: "+b)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var n=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|n:(e&7)<<18|g<<12|n<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var n=a.charCodeAt(++e);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(H.subarray(a,c));c=0;for(d="";;){var e=I[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function sa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)I[b>>1]=a.charCodeAt(e),b+=2;I[b>>1]=0;return b-d}function ta(a){return 2*a.length}function ua(a,b){for(var c=0,d="";!(c>=b/4);){var e=J[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function va(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var n=a.charCodeAt(++e);g=65536+((g&1023)<<10)|n&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,L,H,I,ra,J,M,xa,ya;
function za(a){K=a;h.HEAP8=L=new Int8Array(a);h.HEAP16=I=new Int16Array(a);h.HEAP32=J=new Int32Array(a);h.HEAPU8=H=new Uint8Array(a);h.HEAPU16=ra=new Uint16Array(a);h.HEAPU32=M=new Uint32Array(a);h.HEAPF32=xa=new Float32Array(a);h.HEAPF64=ya=new Float64Array(a)}var Aa=h.INITIAL_MEMORY||16777216;h.wasmMemory?G=h.wasmMemory:G=new WebAssembly.Memory({initial:Aa/65536,maximum:32768});G&&(K=G.buffer);Aa=K.byteLength;za(K);var N,Ba=[],Ca=[],Da=[],Ea=[];
function Fa(){var a=h.preRun.shift();Ba.unshift(a)}var O=0,Ga=null,P=null;h.preloadedImages={};h.preloadedAudios={};function D(a){if(h.onAbort)h.onAbort(a);E(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ha(a){var b=Q;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ia(){return Ha("data:application/octet-stream;base64,")}var Q="jxl_enc.wasm";
if(!Ia()){var Ja=Q;Q=h.locateFile?h.locateFile(Ja,A):A+Ja}function Ka(){try{if(F)return new Uint8Array(F);if(B)return B(Q);throw"both async and sync fetching of the wasm failed";}catch(a){D(a)}}function La(){return F||!y&&!z||"function"!==typeof fetch||Ha("file://")?Promise.resolve().then(Ka):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Ka()})}
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.ga;"number"===typeof c?void 0===b.$?N.get(c)():N.get(c)(b.$):c(void 0===b.$?null:b.$)}}}function Na(a){this.V=a-16;this.sa=function(b){J[this.V+8>>2]=b};this.pa=function(b){J[this.V+0>>2]=b};this.qa=function(){J[this.V+4>>2]=0};this.oa=function(){L[this.V+12>>0]=0};this.ra=function(){L[this.V+13>>0]=0};this.la=function(b,c){this.sa(b);this.pa(c);this.qa();this.oa();this.ra()}}function Oa(){return 0<Oa.da}
var Pa={};function Qa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ra(a){return this.fromWireType(M[a>>2])}var R={},S={},Sa={};function Ta(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ua(a,b){a=Ta(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Va(a){var b=Error,c=Ua(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Wa=void 0;
function Xa(a,b,c){function d(m){m=c(m);if(m.length!==a.length)throw new Wa("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],m[k])}a.forEach(function(m){Sa[m]=b});var e=Array(b.length),g=[],n=0;b.forEach(function(m,k){S.hasOwnProperty(m)?e[k]=S[m]:(g.push(m),R.hasOwnProperty(m)||(R[m]=[]),R[m].push(function(){e[k]=S[m];++n;n===g.length&&d(e)}))});0===g.length&&d(e)}
function Ya(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Za=void 0;function U(a){for(var b="";H[a];)b+=Za[H[a++]];return b}var $a=void 0;function V(a){throw new $a(a);}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(S.hasOwnProperty(a)){if(c.ka)return;V("Cannot register type '"+d+"' twice")}S[a]=b;delete Sa[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(function(e){e()}))}var ab=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function bb(a){4<a&&0===--W[a].aa&&(W[a]=void 0,ab.push(a))}function cb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ab.length?ab.pop():W.length;W[b]={aa:1,value:a};return b}}function db(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function eb(a,b){switch(b){case 2:return function(c){return this.fromWireType(xa[c>>2])};case 3:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function fb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ua(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function gb(a,b){var c=h;if(void 0===c[a].S){var d=c[a];c[a]=function(){c[a].S.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].S+")!");return c[a].S[arguments.length].apply(this,arguments)};c[a].S=[];c[a].S[d.ea]=d}}
function hb(a,b,c){h.hasOwnProperty(a)?((void 0===c||void 0!==h[a].S&&void 0!==h[a].S[c])&&V("Cannot register public name '"+a+"' twice"),gb(a,a),h.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),h[a].S[c]=b):(h[a]=b,void 0!==c&&(h[a].Ba=c))}function ib(a,b){for(var c=[],d=0;d<a;d++)c.push(J[(b>>2)+d]);return c}
function jb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var e;-1!=a.indexOf("j")?e=c&&c.length?h["dynCall_"+a].apply(null,[b].concat(c)):h["dynCall_"+a].call(null,b):e=N.get(b).apply(null,c);return e}}function X(a,b){a=U(a);var c=-1!=a.indexOf("j")?jb(a,b):N.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}
var kb=void 0;function lb(a){a=mb(a);var b=U(a);Z(a);return b}function nb(a,b){function c(g){e[g]||S[g]||(Sa[g]?Sa[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new kb(a+": "+d.map(lb).join([", "]));}
function ob(a,b,c){switch(b){case 0:return c?function(d){return L[d]}:function(d){return H[d]};case 1:return c?function(d){return I[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return M[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var pb={};function qb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function rb(a,b){var c=S[a];void 0===c&&V(b+" has unknown type "+lb(a));return c}var sb={},tb={};
function ub(){if(!vb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in tb)a[b]=tb[b];var c=[];for(b in a)c.push(b+"="+a[b]);vb=c}return vb}var vb,wb=[null,[],[]];function xb(a){return 0===a%4&&(0!==a%100||0===a%400)}function yb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var zb=[31,29,31,30,31,30,31,31,30,31,30,31],Ab=[31,28,31,30,31,30,31,31,30,31,30,31];function Bb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(xb(a.getFullYear())?zb:Ab)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Cb(a,b,c,d){function e(f,l,u){for(f="number"===typeof f?f.toString():f||"";f.length<l;)f=u[0]+f;return f}function g(f,l){return e(f,l,"0")}function n(f,l){function u(C){return 0>C?-1:0<C?1:0}var v;0===(v=u(f.getFullYear()-l.getFullYear()))&&0===(v=u(f.getMonth()-l.getMonth()))&&(v=u(f.getDate()-l.getDate()));return v}function m(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function k(f){f=Bb(new Date(f.R+1900,0,1),f.Z);var l=new Date(f.getFullYear()+1,0,4),u=m(new Date(f.getFullYear(),0,4));l=m(l);return 0>=n(u,f)?0>=n(l,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var p=J[d+40>>2];d={ya:J[d>>2],xa:J[d+4>>2],X:J[d+8>>2],W:J[d+12>>2],U:J[d+16>>2],R:J[d+20>>2],Y:J[d+24>>2],Z:J[d+28>>2],Ca:J[d+32>>2],wa:J[d+36>>2],
za:p?p?ma(H,p,void 0):"":""};c=c?ma(H,c,void 0):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");p={"%a":function(f){return r[f.Y].substring(0,3)},"%A":function(f){return r[f.Y]},"%b":function(f){return x[f.U].substring(0,3)},"%B":function(f){return x[f.U]},"%C":function(f){return g((f.R+1900)/100|0,2)},"%d":function(f){return g(f.W,2)},"%e":function(f){return e(f.W,2," ")},"%g":function(f){return k(f).toString().substring(2)},"%G":function(f){return k(f)},"%H":function(f){return g(f.X,2)},"%I":function(f){f=
f.X;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":function(f){return g(f.W+yb(xb(f.R+1900)?zb:Ab,f.U-1),3)},"%m":function(f){return g(f.U+1,2)},"%M":function(f){return g(f.xa,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.X&&12>f.X?"AM":"PM"},"%S":function(f){return g(f.ya,2)},"%t":function(){return"\t"},"%u":function(f){return f.Y||7},"%U":function(f){var l=new Date(f.R+1900,0,1),u=0===l.getDay()?l:Bb(l,7-l.getDay());f=new Date(f.R+1900,f.U,f.W);return 0>n(u,f)?g(Math.ceil((31-u.getDate()+
(yb(xb(f.getFullYear())?zb:Ab,f.getMonth()-1)-31)+f.getDate())/7),2):0===n(u,l)?"01":"00"},"%V":function(f){var l=new Date(f.R+1901,0,4),u=m(new Date(f.R+1900,0,4));l=m(l);var v=Bb(new Date(f.R+1900,0,1),f.Z);return 0>n(v,u)?"53":0>=n(l,v)?"01":g(Math.ceil((u.getFullYear()<f.R+1900?f.Z+32-u.getDate():f.Z+1-u.getDate())/7),2)},"%w":function(f){return f.Y},"%W":function(f){var l=new Date(f.R,0,1),u=1===l.getDay()?l:Bb(l,0===l.getDay()?1:7-l.getDay()+1);f=new Date(f.R+1900,f.U,f.W);return 0>n(u,f)?g(Math.ceil((31-
u.getDate()+(yb(xb(f.getFullYear())?zb:Ab,f.getMonth()-1)-31)+f.getDate())/7),2):0===n(u,l)?"01":"00"},"%y":function(f){return(f.R+1900).toString().substring(2)},"%Y":function(f){return f.R+1900},"%z":function(f){f=f.wa;var l=0<=f;f=Math.abs(f)/60;return(l?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.za},"%%":function(){return"%"}};for(q in p)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),p[q](d)));q=Db(c);if(q.length>b)return 0;L.set(q,a);return q.length-1}
Wa=h.InternalError=Va("InternalError");for(var Eb=Array(256),Fb=0;256>Fb;++Fb)Eb[Fb]=String.fromCharCode(Fb);Za=Eb;$a=h.BindingError=Va("BindingError");h.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};kb=h.UnboundTypeError=Va("UnboundTypeError");function Db(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}Ca.push({ga:function(){Gb()}});
var Ib={q:function(a){return Hb(a+16)+16},D:function(){},p:function(a,b,c){(new Na(a)).la(b,c);"uncaught_exception"in Oa?Oa.da++:Oa.da=1;throw a;},m:function(a){var b=Pa[a];delete Pa[a];var c=b.ma,d=b.na,e=b.ba,g=e.map(function(n){return n.ja}).concat(e.map(function(n){return n.ua}));Xa([a],g,function(n){var m={};e.forEach(function(k,p){var q=n[p],r=k.ha,x=k.ia,f=n[p+e.length],l=k.ta,u=k.va;m[k.fa]={read:function(v){return q.fromWireType(r(x,v))},write:function(v,C){var Y=[];l(u,v,f.toWireType(Y,
C));Qa(Y)}}});return[{name:b.name,fromWireType:function(k){var p={},q;for(q in m)p[q]=m[q].read(k);d(k);return p},toWireType:function(k,p){for(var q in m)if(!(q in p))throw new TypeError('Missing field:  "'+q+'"');var r=c();for(q in m)m[q].write(r,p[q]);null!==k&&k.push(d,r);return r},argPackAdvance:8,readValueFromPointer:Ra,T:d}]})},z:function(a,b,c,d,e){var g=Ya(c);b=U(b);T(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,m){return m?d:e},argPackAdvance:8,readValueFromPointer:function(n){if(1===
c)var m=L;else if(2===c)m=I;else if(4===c)m=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[n>>g])},T:null})},y:function(a,b){b=U(b);T(a,{name:b,fromWireType:function(c){var d=W[c].value;bb(c);return d},toWireType:function(c,d){return cb(d)},argPackAdvance:8,readValueFromPointer:Ra,T:null})},j:function(a,b,c){c=Ya(c);b=U(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+
db(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:eb(b,c),T:null})},l:function(a,b,c,d,e,g){var n=ib(b,c);a=U(a);e=X(d,e);hb(a,function(){nb("Cannot call "+a+" due to unbound types",n)},b-1);Xa([],n,function(m){var k=[m[0],null].concat(m.slice(1)),p=m=a,q=e,r=k.length;2>r&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==k[1]&&!1,f=!1,l=1;l<k.length;++l)if(null!==k[l]&&void 0===k[l].T){f=!0;break}var u="void"!==k[0].name,v=
"",C="";for(l=0;l<r-2;++l)v+=(0!==l?", ":"")+"arg"+l,C+=(0!==l?", ":"")+"arg"+l+"Wired";p="return function "+Ta(p)+"("+v+") {\nif (arguments.length !== "+(r-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(r-2)+" args!');\n}\n";f&&(p+="var destructors = [];\n");var Y=f?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[V,q,g,Qa,k[0],k[1]];x&&(p+="var thisWired = classParam.toWireType("+Y+", this);\n");
for(l=0;l<r-2;++l)p+="var arg"+l+"Wired = argType"+l+".toWireType("+Y+", arg"+l+"); // "+k[l+2].name+"\n",v.push("argType"+l),q.push(k[l+2]);x&&(C="thisWired"+(0<C.length?", ":"")+C);p+=(u?"var rv = ":"")+"invoker(fn"+(0<C.length?", ":"")+C+");\n";if(f)p+="runDestructors(destructors);\n";else for(l=x?1:2;l<k.length;++l)r=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==k[l].T&&(p+=r+"_dtor("+r+"); // "+k[l].name+"\n",v.push(r+"_dtor"),q.push(k[l].T));u&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");
v.push(p+"}\n");k=fb(v).apply(null,q);l=b-1;if(!h.hasOwnProperty(m))throw new Wa("Replacing nonexistant public symbol");void 0!==h[m].S&&void 0!==l?h[m].S[l]=k:(h[m]=k,h[m].ea=l);return[]})},d:function(a,b,c,d,e){function g(p){return p}b=U(b);-1===e&&(e=4294967295);var n=Ya(c);if(0===d){var m=32-8*c;g=function(p){return p<<m>>>m}}var k=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+db(q)+
'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+db(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return k?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:ob(b,n,0!==d),T:null})},c:function(a,b,c){function d(g){g>>=2;var n=M;return new e(K,n[g+1],n[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{ka:!0})},k:function(a,b){b=U(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=M[d>>2];if(c)for(var g=d+4,n=0;n<=e;++n){var m=d+4+n;if(n==e||0==H[m]){g=g?ma(H,g,m-g):"";if(void 0===k)var k=g;else k+=String.fromCharCode(0),k+=g;g=m+1}}else{k=Array(e);for(n=0;n<e;++n)k[n]=String.fromCharCode(H[d+4+n]);k=k.join("")}Z(d);return k},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||
e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var n=(c&&g?function(){return oa(e)}:function(){return e.length})(),m=Hb(4+n+1);M[m>>2]=n;if(c&&g)na(e,H,m+4,n+1);else if(g)for(g=0;g<n;++g){var k=e.charCodeAt(g);255<k&&(Z(m),V("String has UTF-16 code units that do not fit in 8 bits"));H[m+4+g]=k}else for(g=0;g<n;++g)H[m+4+g]=e[g];null!==d&&d.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Ra,T:function(d){Z(d)}})},g:function(a,b,c){c=U(c);
if(2===b){var d=qa;var e=sa;var g=ta;var n=function(){return ra};var m=1}else 4===b&&(d=ua,e=va,g=wa,n=function(){return M},m=2);T(a,{name:c,fromWireType:function(k){for(var p=M[k>>2],q=n(),r,x=k+4,f=0;f<=p;++f){var l=k+4+f*b;if(f==p||0==q[l>>m])x=d(x,l-x),void 0===r?r=x:(r+=String.fromCharCode(0),r+=x),x=l+b}Z(k);return r},toWireType:function(k,p){"string"!==typeof p&&V("Cannot pass non-string to C++ string type "+c);var q=g(p),r=Hb(4+q+b);M[r>>2]=q>>m;e(p,r+4,q+b);null!==k&&k.push(Z,r);return r},
argPackAdvance:8,readValueFromPointer:Ra,T:function(k){Z(k)}})},n:function(a,b,c,d,e,g){Pa[a]={name:U(b),ma:X(c,d),na:X(e,g),ba:[]}},h:function(a,b,c,d,e,g,n,m,k,p){Pa[a].ba.push({fa:U(b),ja:c,ha:X(d,e),ia:g,ua:n,ta:X(m,k),va:p})},A:function(a,b){b=U(b);T(a,{Aa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},f:bb,C:function(a){if(0===a)return cb(qb());var b=pb[a];a=void 0===b?U(a):b;return cb(qb()[a])},B:function(a){4<a&&(W[a].aa+=1)},o:function(a,b,c,d){a||V("Cannot use deleted val. handle = "+
a);a=W[a].value;var e=sb[b];if(!e){e="";for(var g=0;g<b;++g)e+=(0!==g?", ":"")+"arg"+g;var n="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)n+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",n+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(rb,
h,cb);sb[b]=e}return e(a,c,d)},b:function(){D()},t:function(a,b,c){H.copyWithin(a,b,b+c)},e:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{G.grow(Math.min(2147483648,d)-K.byteLength+65535>>>16);za(G.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},v:function(a,b){var c=0;ub().forEach(function(d,e){var g=b+c;e=J[a+4*e>>2]=g;for(g=0;g<d.length;++g)L[e++>>
0]=d.charCodeAt(g);L[e>>0]=0;c+=d.length+1});return 0},w:function(a,b){var c=ub();J[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});J[b>>2]=d;return 0},x:function(){return 0},r:function(){},i:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var n=J[b+8*g>>2],m=J[b+(8*g+4)>>2],k=0;k<m;k++){var p=H[n+k],q=wb[a];0===p||10===p?((1===a?ja:E)(ma(q,0)),q.length=0):q.push(p)}e+=m}J[d>>2]=e;return 0},a:G,s:function(){},u:function(a,b,c,d){return Cb(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;N=h.asm.E;O--;h.monitorRunDependencies&&h.monitorRunDependencies(O);0==O&&(null!==Ga&&(clearInterval(Ga),Ga=null),P&&(e=P,P=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){E("failed to asynchronously prepare wasm: "+g);D(g)})}var d={a:Ib};O++;h.monitorRunDependencies&&h.monitorRunDependencies(O);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return E("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return F||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||Ha("file://")||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var Gb=h.___wasm_call_ctors=function(){return(Gb=h.___wasm_call_ctors=h.asm.F).apply(null,arguments)},Hb=h._malloc=function(){return(Hb=h._malloc=h.asm.G).apply(null,arguments)},Z=h._free=function(){return(Z=h._free=h.asm.H).apply(null,arguments)},mb=h.___getTypeName=function(){return(mb=h.___getTypeName=h.asm.I).apply(null,arguments)};h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.J).apply(null,arguments)};
h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.K).apply(null,arguments)};h.dynCall_iiji=function(){return(h.dynCall_iiji=h.asm.L).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.M).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.N).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.O).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.P).apply(null,arguments)};
var Jb;P=function Kb(){Jb||Lb();Jb||(P=Kb)};
function Lb(){function a(){if(!Jb&&(Jb=!0,h.calledRun=!0,!ka)){Ma(Ca);Ma(Da);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ea.unshift(b)}Ma(Ea)}}if(!(0<O)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Fa();Ma(Ba);0<O||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
h.run=Lb;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();noExitRuntime=!0;Lb();


  return jxl_enc.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = jxl_enc;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return jxl_enc; });
    else if (typeof exports === 'object')
      exports["jxl_enc"] = jxl_enc;
    